### ISSUE TITLE
Formatted Text Image Color

### ISSUE THREAD

**Issue by Remixful** [nhmkdev/cardmaker#101]
I'd like to be able to set the color of images in formatted text.

**Comment by nhmkdev** [comment]
I'll probably add in a new tag `<ic=[color definition]>` that will impact images in FormattedText elements (both regular and background images).

**Comment by nhmkdev** [comment]
This functionality is implemented in the latest pre-release: [CardMaker v.1.2.0.0-unstable.v.a9](https://github.com/nhmkdev/cardmaker/releases/tag/v.1.2.0.0-unstable.v.a9)

Example use is included in the sample project.

`<ic=0xFF0000><img=images\gear.png></ic>`
