### ISSUE TITLE
FormattedText Shape Tag

### ISSUE THREAD

**Issue by nhmkdev** [nhmkdev/cardmaker#102]
Allow the creation of shapes inline. They would need to be the font size (by default) and take up space like text/images.

Will this be especially useful?

**Comment by Amas73** [comment]
I haven't tried the define functionality yet for setting icons to use in formatted text. But what happens when they are bigger than font size? Wouldn't the handling be the same?

**Comment by nhmkdev** [comment]
Closing out as stale. Graphics are probably enough for inline.
