### ISSUE TITLE
Custom page size only works for first page

### ISSUE THREAD

**Issue by marcusross** [nhmkdev/cardmaker#106]
I set a custom page size for pdf export larger than 8.5 x 11 and the generated pdf only retained this page size for the first page. Subsequent pages revert to the standard document size.
![pdf export](https://user-images.githubusercontent.com/1551313/189719357-4d347c85-496c-4c60-8308-36ecc92db0fc.png)

**Comment by nhmkdev** [comment]
I believe this was resolved in https://github.com/nhmkdev/cardmaker/releases/tag/v.1.2.0.0-unstable.v.a4

What build are you running? You could try in one of the newer pre-releases if you're running 1.1.0.0.

**Comment by nhmkdev** [comment]
Closing out.
