### ISSUE TITLE
[enhancement] image tint/coloring

### ISSUE THREAD

**Issue by rullinoiz** [nhmkdev/cardmaker#107]
it would be pretty cool if we were able to color or tint images, like an extra argument

**Comment by nhmkdev** [comment]
This actually already exists fortunately! You can set the color on any image element. If you are working with images in FormattedText elements there is a tag "ic" that allows you to specify the color.

This was added in version 1.2.0.0.A2. All of the pre-release builds after also have it.

**Comment by rullinoiz** [comment]
oh damn i'll have to check that out then
