### ISSUE TITLE
Row counter

### ISSUE THREAD

**Issue by warmist** [nhmkdev/cardmaker#108]
I would really like a ![rowindex] counter. This would help correct the csv (i.e. if card has an error just look at the ![rowindex] in the csv)

**Comment by nhmkdev** [comment]
This logic was added with this pre-release: https://github.com/nhmkdev/cardmaker/releases/tag/v.1.3.0.0-unstable.v.a1

From the release description:
- Added reference macros for displaying the reference source line and name `![refline]` and `![refname]`
- The above information is also visible in the window title of the canvas
