### ISSUE TITLE
Add em dash support

### ISSUE THREAD

**Issue by nhmkdev** [nhmkdev/cardmaker#113]
Add support for em dashes to Text and FormattedText elements (if there isn't already a reasonable way to make it appear)

**Comment by CJMenart** [comment]
Update: I went back to check em dashes in Text and FormattedText, per your comment on BGG, and you care correct--they are unrecognized characters in either, seemingly no matter the font.

**Comment by nhmkdev** [comment]
I was able to get em dashes into both Text and FormattedText elements:

Key factors:
* I pasted the em dash character into CardMaker from LibreOffice Writer (into the Definition field)
* I also put the em dash character into a text editor (Textpad) and saved it as UTF-8 format (for use as a reference in CardMaker)
* I'm in Windows 10 and the font on the element is Arial
* In the Definition field editor itself the em dash renders as a normal dash (I think this is likely due to the use of a monospace font)
