### ISSUE TITLE
[Wiki] Not very clear on where the app would be looking for global defines on Google Spreadsheets

### ISSUE THREAD

**Issue by rullinoiz** [nhmkdev/cardmaker#115]
I set up the Google Spreadsheets support and it worked perfectly except for my global defines (projectname_defines) and the [wiki didn't seem to be very clear](https://github.com/nhmkdev/cardmaker/wiki/user-references-google#cardmaker-setup) on what name it's checking for. I decided to [look through the source code](https://github.com/nhmkdev/cardmaker/blob/master/CardMaker/Card/Import/GoogleReferenceReader.cs#L41) to find out that it's just named `defines` and assumed it was supposed to be named `projectname_defines` in a new sheet or whole new spreadsheet

It would be very nice if this was cleared up because I'm sure a lot of other people probably had the same revelation as me (some not so lucky because they probably don't know how to read C#)

**Comment by nhmkdev** [comment]
The latest manual has a better description than the wiki (I think the pre-releases have the improved version). I'll migrate that over to the wiki.

Older versions of the app may included a more dated manual with a much rougher description.
