### ISSUE TITLE
Stitched Export Misaligned with Off-Canvas Content

### ISSUE THREAD

**Issue by jmb496** [nhmkdev/cardmaker#118]
I'm surprised I haven't run into this before, but I guess I've taken bigger shortcuts here by positioning an image significantly off-canvas to the top left instead of cropping it.  Export to png works great as long as it's only 1 image, but if I stitch 2x2 or 3x3, each exported image in the grid appears to begin at the top-left most element origin (even when off canvas), keeping the height/width as intended, which cuts off the bottom-right.

 
![Planets_02](https://github.com/nhmkdev/cardmaker/assets/1682655/c64080ce-91b6-4e23-8546-66529e1dfcff)
![Planets_04](https://github.com/nhmkdev/cardmaker/assets/1682655/0521d857-da41-40a9-bf58-7a1441b7928a)

**Comment by jmb496** [comment]
Ahh.  Looking closer, I wasn't exactly right with my assessment above - looks like the whole canvas is displayed, but the right and bottommost images overlay those above and to the left, which cuts off those.

**Comment by nhmkdev** [comment]
Which version of CardMaker did you hit this in? There was a related fix that went into [v.1.3.0.0-unstable.v.a5](https://github.com/nhmkdev/cardmaker/releases/tag/v.1.3.0.0-unstable.v.a5)

Fix: 
https://github.com/nhmkdev/cardmaker/commit/09aeb7d33868cf9b10f8c8252e2a4468b39a6a2b

**Comment by jmb496** [comment]
1.2.0.0
I'll check out 1.3

**Comment by jmb496** [comment]
Confirmed this is fixed in [v.1.3.0.0-unstable.v.a5](https://github.com/nhmkdev/cardmaker/releases/tag/v.1.3.0.0-unstable.v.a5)
