### ISSUE TITLE
[Request] Support nested if statements

### ISSUE THREAD

**Issue by nhmkdev** [nhmkdev/cardmaker#12]
If possible it would be useful in some situations to support nested if statements.

**Comment by ericraue** [comment]
Some additional features could be supporting and/or/not similar to spreadsheets. Syntax could be as followed. The "not" operator isn't that useful but helps negate a complex conditional quickly.
```
#(if and(@[strength] > 4, @[strength] < 10, @[type] == ally) then something else #nodraw)#
#(if and(or(@[strength] < 4, @[strength] > 10), @[type] == ally) then something else #nodraw)#
```

**Comment by nhmkdev** [comment]
On this subject I have considered in the past supporting JavaScript as a Definition value. This would eliminate the need to maintain and improve a scripting system that is, for lack of a nicer word, pretty close to "garbage." Any opinions on the matter? I am tempted to add it in and make it optional (maybe a check box on a per element basis to indicate the definition is JavaScript vs. the "old style").

**Comment by ericraue** [comment]
Revamping or replacing the scripting language is not a bad idea. Regarding upgrading old projects, the project file could have a version number and warn when loading old projects, do partial patching etc. Both could be separate github issues to discuss them.
