### ISSUE TITLE
Unable to load google sheet

### ISSUE THREAD

**Issue by Blkx-Darkreaper** [nhmkdev/cardmaker#120]
When I add a google sheet as a reference in a layout I get the following errors:
No defines found for project file: g:\Users\Darkreaper\Documents\Projects\Axis and Allies\Card Combat System\AADDayCards.cmp
CSV File not found: g:\Users\Darkreaper\Documents\Projects\Axis and Allies\Card Combat System\..\..\..\..\..\..\..\google;AADDayCards;Test;1HXqk5Mo3w_ke3Fc08ejXOW9h3eRVg8_UgZNx93ulqNk

However if I remove the reference then Cardmaker finds the defines automatically since it follows the proper naming. I've tried with different projects, sheet names, etc but can't get the sheet data to load into Cardmaker successfully. I'm using v1.2.0.0

**Comment by nhmkdev** [comment]
Quick check: Are you referring to the project-wide defines Google override? (Layouts > Project Settings...)

If so, be sure to set the `Default Define Reference Type` to Google.

---

The error looks very odd: `g:\Users\Darkreaper\Documents\Projects\Axis and Allies\Card Combat System..............\google;AADDayCards;Test;1HXqk5Mo3w_ke3Fc08ejXOW9h3eRVg8_UgZNx93ulqNk` Are the `....` characters actually in the log or are you just keeping that private (very understandable if so)?

In the `.cmp` file you can find the google reference on a layout. It should look something like this:
`<Reference RelativePath="google;Data;SomeCards;(bunch of random characters)" Default="true" />`
^^ this is an example from my local cmp file

You could try a newer version like https://github.com/nhmkdev/cardmaker/releases/tag/v.1.3.0.0-unstable.v.a7 temporarily and see if that makes any difference.

**Comment by Blkx-Darkreaper** [comment]
I was using the override to see if that fixed the issue, but then removed it. Had it set to Google as well. Neither option made any difference as far as loading the non defines data is concerned

Those are the actual errors I got. The only parts I removed were the time stamps

This is the reference in the project file:
<Reference RelativePath="..\..\..\..\..\..\..\google;AADDayCards;cards;1HXqk5Mo3w_ke3Fc08ejXOW9h3eRVg8_UgZNx93ulqNk" Default="true" />

**Comment by Blkx-Darkreaper** [comment]
With version 1.3.0.0 I get the following errors:
CSV File not found: C:\Users\Darkreaper\Desktop\..\..\..\..\..\..\..\google;AADDayCards;cards;1HXqk5Mo3w_ke3Fc08ejXOW9h3eRVg8_UgZNx93ulqNk
WARNING: The reference AADDayCards.defines is missing the Spreadsheet ID. Please reconfigure this reference.

The defines do load in even with the reference under this version though

**Comment by nhmkdev** [comment]
Hmm it looks like there's nothing after your "This is the reference in the project file:" message above.

Just based on the error log it looks like the reference is being prefixed oddly (the first thing should be `google;[other stuff]...`). You could manually edit it and removing anything before `google;` in the `RelativePath` quoted value.

This is the first time I've seen the many `......` characters happen to anyone! 🤣 Which version of windows are you running?

Aside: Some people have had difficulty with storing projects on the desktop. It seems to work fine for me. There can definitely be permissions and otherwise issues.

**Comment by Blkx-Darkreaper** [comment]
Removing the prefix from the relative path fixed the issue. Any ideas why that got appended in the first place?

**Comment by nhmkdev** [comment]
The only possibility would be a bug with merging two references (one that was a CSV path and then the Google reference). As I've never seen it before it's definitely an odd one!

Based on the odd prefix `..............\` it looks like the app attempted to create a relative path to the google spreadsheet. That's pretty crazy! 😵

Does it seem to happen every time you add a google reference or only in this specific instance?

**Comment by Blkx-Darkreaper** [comment]
I tried creating references multiple times. Even to different google sheets trying to identify the issue. I always got the same failure message so I'm guessing it happens every time

**Comment by nhmkdev** [comment]
Slightly related: Google policies around security are forcing me to make changes to the application.

There is also a risk that the entire use of Google Spreadsheets may break (at worst have to be completely removed).

**Comment by Blkx-Darkreaper** [comment]
:( I just got it working and it's such a great feature. I hope you're able to keep it working

**Comment by nhmkdev** [comment]
Closing this out at this time.
