### ISSUE TITLE
PDF export of a specific selection of cards

### ISSUE THREAD

**Issue by AWoodward96** [nhmkdev/cardmaker#124]
I like using Card Maker for prototyping purposes. 

Often times after a number of playtests there will be specific cards that need changes, and a whole lot of cards that are just fine as is. It would be nice to be able to open a dialog window and manually select the changed cards for export in order to save on paper when iterating.

A further development of a system like this would be to be able to track changes automatically, but ultimately this is a free program so I'll take what I can get.

**Comment by nhmkdev** [comment]
I've hit this too... where I just want to export a subset of cards. Other than changing the card count in the reference to 0 for the cards you don't need nothing currently would help much (some people sometimes swap the count column in their reference to simplify this approach.)

* I think the simplest version of this would be to offer a way to specify the cards to export via numbers (of course that doesn't include a preview).
* The better way would be a window where you could see previews and select those you want.

**Comment by MarkVabulas** [comment]
With previews and selections, it sounds great until you have to generate all of those cards again (some of my individual layout exports can take 15 minutes) and then individually select each image, to then recombine into another layout, yet more time.

The basic windows print dialog allows people to type individual numbers, or ranges of numbers, comma separated.   Such as:
`1,9-23,17,4,6`

And that will print 19 pages, and ordered as stated above.

**Comment by nhmkdev** [comment]
Point of some humor: The command line supports specifying the card to export via `-cardIndices` (see manual). I need to add it to the UI.

**Comment by nhmkdev** [comment]
Note to self: Beware of the special functionality for PDFs like card backs. This may impact how `cardIndices` would function with pdf exports. Also `cardIndices` is not supported on the command line export of PDFs.

**Comment by Blkx-Darkreaper** [comment]
Additionally would be helpful if you could choose to just export those images for certain Layouts instead of the entire project

**Comment by nhmkdev** [comment]
Note: You can export individual layouts or cards from a layout by right-clicking in the Project dialog on a layout and select `Export Card Layout [pdf/images]...`

Basic index string style support via the export dialog will be in the next pre-release version for PDFs/images https://github.com/nhmkdev/cardmaker/commit/10510600030d3bdf456572ba235c59c077ab4226

**Comment by nhmkdev** [comment]
Added with pre-release: https://github.com/nhmkdev/cardmaker/releases/tag/v.1.4.0.0-unstable.v.a2
