### ISSUE TITLE
Excel references do not support relative paths

### ISSUE THREAD

**Issue by nhmkdev** [nhmkdev/cardmaker#125]
[Originally mentioned here](https://boardgamegeek.com/thread/3248507/help-requested-prep-card-maker-1300)

Humorously... this is a complicated thing to fix!

**Comment by nhmkdev** [comment]
This has likely been addressed and will be in version pre-release 1.4.0.0.A1.

**Comment by MarkVabulas** [comment]
Do you develop on head, or is there a different branch if I want to be an alpha tester?

**Comment by nhmkdev** [comment]
Mostly on head unless it's super dangerous. The changes have been merged so you can pull it down & build. Be sure to backup your project just in case it wrecks something! 😟 

I'll be doing another test pass sometime soon and then make a new release.

**Comment by nhmkdev** [comment]
Should be part of the latest pre-release: https://github.com/nhmkdev/cardmaker/releases/tag/v.1.4.0.0-unstable.v.a1
