### ISSUE TITLE
[Feature Request] Creation of a <center></center> tag pair in FormattedText

### ISSUE THREAD

**Issue by MarkVabulas** [nhmkdev/cardmaker#127]
Would it be possible to allow for conditional toggling of horizontal centering for lines encapsulated inside a \<center /> tag pair?  It's currently possible to do horizontal centering as a whole block, but not conditionally.  

Typically, to ease implementation, it usually requires there is a newline/\<br> immediately preceding the \<center> open tag, or that one is inserted if it's missing.  This could simplify the text flow.  

There are many use cases for having a block of text, followed by an inline-centered-image or text on a separate row(s), following by more left-justified text, for example.  If you point me in the right direction, I might be able to help with this if you have an idea where to look to implement it.

**Comment by nhmkdev** [comment]
Would the align center tag `<ac>` work for this? I opted for a different name for the alignment tags: `ac, al, ar`
```
title<br><ac>information</ac><br>subtext
```

Hmm, I might be misunderstanding though!

**Comment by MarkVabulas** [comment]
Is there documentation somewhere other than this wiki about the available tags we can use in FormattedText?  I wasn't aware of \<ac />!

**Comment by MarkVabulas** [comment]
But yes, \<ac /> is exactly what I was looking for.

**Comment by nhmkdev** [comment]
There is documentation included in the zip with every built release: https://github.com/nhmkdev/cardmaker/releases

`Card_Maker.pdf` has a lot of information 🧐 

You can also find the odt file(s) if you are just pulling the source: https://github.com/nhmkdev/cardmaker/tree/master/CardMaker/bin/Release
