### ISSUE TITLE
[Feature Request] Place a point instead of a region, and center an image on that point

### ISSUE THREAD

**Issue by MarkVabulas** [nhmkdev/cardmaker#128]
Would it be possible to change from using regions to using a single point in certain instances, and then center the contents of the field on that location?  This would be functionally equivalent to having height==0 && width==0 && horizontal_align==center && vertical_align==middle, except it would allow for the contents to *overdraw* into the surrounding space... 

It could mean placing many different images of varying shapes/sizes, but with the same orthocenter, in the same location without having to compromise on the placement....

**Comment by nhmkdev** [comment]
I might be misunderstanding so a couple of thoughts/questions: What element type are you referring to? With a graphic element you should be able to something equivalent to this now with aligning center/middle with an oversized element to allow for any image shape/size.

I think I've hit a few cases where working with center would have been nice, but I would probably create entirely new types of elements as there's generally a lot of complexity from having to work with regions/bounds.

**Comment by MarkVabulas** [comment]
So I have a lot (think hundreds to thousands) of graphical elements that came from other volunteers (so I can't just easily ask them to go make changes) where the center of the object in the image isn't necessarily the center pixel.  What I'm trying to do is place the image at a certain place, and then offset it by a certain amount.  Trying to calculate this in the scripts gets messy and breaks with non-integer data (#129) from trying to scale and center the images.  It's much easier to set card_offset+center pixel and then #math;dimensions*scaling_factor;0#.  When I've tried to find the correct x/y coordinate using the corner instead of the center, it gets too messy for the scripting to handle, and I think I have too many layouts with too much going on so far to just switch to javascript at this point.

One possible solution as a workaround would be to allow token replacement of `$[variable]` be a replacement for the current value, instead of assignment-only.  An easy test case is `$[y:$[x]]`, which would guarantee that the object would always lie on the 1-slope line from the origin.  From looking through the code, it seems like it might just be adding a regex and a replacement, but I don't know better how the system is setup and didn't have the time to try to implement it.  With guidance I can do the coding part and submit a PR.  I don't think there would be self-referential issue writing `$[x:#math;$[x]+$[x]#]` because it would be replaced by the current value of x in both places before being added and then re-assigned, right?

**Comment by nhmkdev** [comment]
Making the element fields available for use definitely seems like a good idea. I did a quick local prototype and was able to use this:

```
$[x:#math;&[x]-5#]
```
The result was the element drew at an offset of `-5`. I'll probably go with `&[...]` for referencing fields.

**Comment by nhmkdev** [comment]
The first draft of this has been merged. It has almost no testing... that comes next!

**Comment by MarkVabulas** [comment]
This is gonna be so great!  Any chance of getting graphical overdraw outside of the bounds, which would make these changes more effective for my use case?

**Comment by nhmkdev** [comment]
Here's my current thinking on what new functionality might help and enable other interesting use cases. 

Graphic Elements will have a new checkbox: Center Image on Element Origin

When checked with the following:
* **Lock Aspect Ratio**: Renders the image based on the **element** width/height (with aspect ratio)
* Nothing checked: Renders the image based on the **element** width/height (with no regard for aspect ratio)
* **Keep Original Size**: Renders the image based on the **image** width/height (aspect ratio will match image)

In all cases the center of the image will be at the x/y value of the element (based on the above information). CardMaker will open the image file and use the width/height to perform the basic math of getting the center for offset translation/rendering.

I think in your use case you would use **Center Image on Element Origin** + **Keep Original Size**
* then additionally providing offsets for the x/y value per image

Aside: It sounds like the offset part of your effort is a ton of work! 😨

**Comment by nhmkdev** [comment]
Center On Origin has been merged. I'll test further before making a new binary release. The manual has been updated with the basic information about accessing fields via `&[x]` and the `Center On Origin` functionality on a Graphic Element.

**Comment by MarkVabulas** [comment]
This all sounds great.  I'll check out the new functionality and let you know!

**Comment by MarkVabulas** [comment]
Works great, thanks!
