### ISSUE TITLE
[Bug] Using #math# to do calculations resulting in decimals breaks positional overrides

### ISSUE THREAD

**Issue by MarkVabulas** [nhmkdev/cardmaker#129]
Coming from a spreadsheet with a column value Scaling_Factor:1.5, this will break the calculations:
$[x:#10*@[Scaling_Factor]#]

The same Scaling_Factor set to whole numbers of 1 or 2 will work correctly.  This means some instances of the layout are consistent and others have the x-value set to 0.

The expected value should be 10*1.5, or 15.  Would it be possible to make sure that the conversion back to the overridden position includes a rounding operation?

**Comment by nhmkdev** [comment]
I tried to repro this and was unable to (excel file, unit test, and just manually in a couple elements).

In the Tools > Settings... you can turn on the "Log Incept Translation" functionality to view the translation step by step. This may help reveal any issues. It will log the next time an element translation is required.

**Comment by MarkVabulas** [comment]
The log Incept did seem to help.  I also went a slightly different direction.  It looked like decimals of more than 4 sigfig would break, unless I tossed a ;0 on the end of the math.  But I can't reproduce it anymore.
