### ISSUE TITLE
[Feature Request] Gradient coloring

### ISSUE THREAD

**Issue by MarkVabulas** [nhmkdev/cardmaker#131]
So currently we have access to element coloring for things like text rendering.  Would it be possible to allow for a second color selection, and a principal direction, which would perform a gradient across the total size of the element, fading from the first color to the second color?  Ideas for directions would be uniquely horizontal, vertical, and the two diagonals.  I realize these might also benefit from adding them to the scripting side of things.  

Furthermore, since I see you're using the .Net Graphics API, because of the alpha values in the hex colors, really cool effects could be achieved which are otherwise currently impossible.  Image fading, text gradients, etc.  

If you could tell me where I should look into adding this to the UI and what file to look into for incorporating the rendering aspect, I'd love to try to assist with the coding.

**Comment by nhmkdev** [comment]
For learning and rough planning I would just use a graphic element and add in a function when the file cannot be found to attempt to draw based on parsing the definition/variable text... Injecting the code here: https://github.com/nhmkdev/cardmaker/blob/master/CardMaker/Card/DrawGraphic.cs#L44-L48

Ultimately I would probably recommend creating a new element type to allow for custom drawing like you're describing. Type processors are setup here: https://github.com/nhmkdev/cardmaker/blob/master/CardMaker/Card/CardRenderer.cs & https://github.com/nhmkdev/cardmaker/blob/master/CardMaker/Card/Render/TypeElementRenderProcessor.cs

I think one concern I have always battled is that while CardMaker can provide a lot of neat things... there will always be something more that someone wants to do that is better handled in a professional image manipulation tool (GIMP, Photoshop, Illustrator). 🤔

**Comment by MarkVabulas** [comment]
I'll get looking into those things there.  And as for using professional editors, for example in my Event Cards repository, I have 160 unique events I'm using to extend a game.  Each title is unique, and if I want to follow the conventions of the titles of the cards, it should have a color gradient applied across the text as a fade from the base color to white (in my case, a light blue to white fade across the text).  I'd prefer not to have to manually make 160 different images just for the titles of these cards, and if there was a typo or a name needed to change then I would be forced to redo image editing... that's a huge burden when a more automated method would work great (i.e. CardMaker).

Possibly in Gimp/illustrator/Photoshop there are ways of doing data-driven image outputs, but that requires knowing more techniques and dealing with multiple programs and multiple stages of a pipeline for making new assets.

Thank you for the wonderful work you've already done, and I'll start looking into what I can hack together (if it's possible).

**Comment by MarkVabulas** [comment]
You can see in the title here, that the yellow->white fade is an example of the gradient in action

![Action_23](https://github.com/nhmkdev/cardmaker/assets/1007185/6a6380ad-6100-4310-a3f6-0895b8ff14db)

**Comment by nhmkdev** [comment]
Closing out. Wish list ticket exists for whenever I feel like expanding the functionality: https://github.com/nhmkdev/cardmaker/issues/133
