### ISSUE TITLE
Adding Webp for images

### ISSUE THREAD

**Issue by GabrielMPhi** [nhmkdev/cardmaker#134]
Firstly, I'd like to express my appreciation for the app. It has become an indispensable tool for my tabletop RPG games, enhancing our gaming experience significantly. The functionality and ease of use are commendable.

However, I'd like to suggest an enhancement that could further improve the app's versatility and user experience. Currently, the application supports image formats like JPG and PNG, which has been incredibly useful. Would it be possible to extend this support to include .webp images as well? The .webp format offers superior compression and quality characteristics, which could greatly benefit users who are mindful of storage and loading times without compromising image quality.

**Comment by nhmkdev** [comment]
It looks like .NET 7 supports the webp format. I could investigate upgrading the application to a newer version (probably .NET 8).

Based on my prior experiences upgrades have gone terribly. 🤣

**Comment by nhmkdev** [comment]
Update: .NET 8 doesn't actually support WebP. I'm investigating using https://github.com/mono/SkiaSharp and so far it is promising (just not for the mono build).

**Comment by nhmkdev** [comment]
I was focused primarily on import of webp images. Are you interested in export as well?

**Comment by nhmkdev** [comment]
Export logic added. Will be included in the next pre-release (probably 1.4.0.0 A2)

**Comment by nhmkdev** [comment]
Added with https://github.com/nhmkdev/cardmaker/releases/tag/v.1.4.0.0-unstable.v.a2
