### ISSUE TITLE
Export images range numbers issues

### ISSUE THREAD

**Issue by MarkVabulas** [nhmkdev/cardmaker#136]
When running the individualized output for each given layout, when specifying a range which doesn't include the card numbers, the software throws and quits.  My suggestion is to truncate the range to the valid range.  

I entered the range 0-8 on a group of 8 cards, and got the error.  It seems that the check inside FileCardExporter.cs:232 could just be amended to be inside the valid range.  Someone writing 0-50000 on 50 cards probably just wants them all....

Secondly, if the box is left blank, then no export currently takes place.  The default should either fill the box in for the user; additionally, it makes sense to still do a complete export if the box is empty, rather than just closing the window with no feedback to the user. 

Alternatively, an invalid value in the box (such as empty) could show a message box to the user explaining it?  Though that seems more inconvenient than just truncating the range to the valid range and assuming the default should be a total export of the selected layout.

**Comment by nhmkdev** [comment]
This one should be fixed: `Secondly, if the box is left blank, then no export currently takes place` (https://github.com/nhmkdev/cardmaker/commit/36a953f2c106407000430b1ea16f36adae7c2605)

Yea I thought the original command line version clamped the end so I'll have to fix any out of bounds values.

**Comment by nhmkdev** [comment]
Clamping done: https://github.com/nhmkdev/cardmaker/commit/35b92d1ee36600b8bf600f00869bede0996b56c0

**Comment by MarkVabulas** [comment]
Confirmed that everything is working now.  Great job!
