### ISSUE TITLE
Google Spreadsheet Access Exception. HttpStatusCode is Forbidden. Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by Blkx-Darkreaper** [nhmkdev/cardmaker#143]
Still having issues with Google sheets and getting some very odd behaviour. It doesn't appear to be behaving like it's unable to connect to google, just that it can't load everything in properly

```
WARNING: The reference AADDayCards.defines is missing the Spreadsheet ID. Please reconfigure this reference.
Google Spreadsheet access exception: The service drive has thrown an exception. HttpStatusCode is Forbidden. Request had insufficient authentication scopes.
Failed to load any data from Google Spreadsheet.[AADDayCards,defines]
No defines found for project file: g:\Users\Darkreaper\Documents\Projects\Axis and Allies\Card Combat System\AADDayCards.cmp
``` 
The data for the first page loads and the total number of cards loads correctly but all cards after the first entry in the sheet don't load properly. The defines specific to the layout (cards_defines) loads but not the project defines (defines)
![image](https://github.com/nhmkdev/cardmaker/assets/8000312/324a330b-19d3-4035-b98a-0727ef3da67a)

This is from version 1.3.0.0

**Comment by nhmkdev** [comment]
That is very odd. 😞  I know Google is messing with their authorization a lot so you may have to remove access for CardMaker and then restore it once. This is the page I used to remove access (you'll be prompted to grant access again next time you get a token for CardMaker): https://myaccount.google.com/connections

I am surprised only the first row works. That's the first I've heard of that!

Have you tried reconfiguring the Project level defines via: right-click Layouts > Project Settings... and then selected Google as the default define reference type (and then specified the `Google Project define spreadsheet override`)?

**Comment by Blkx-Darkreaper** [comment]
Setting the Google project define spreadsheet override appears to be the fix that was required. I tried the other suggestions but they didn't appear to make a difference, or it was the combination of all of them that resolved the issue
