### ISSUE TITLE
Change how ElementColor is applied to Images

### ISSUE THREAD

**Issue by MarkVabulas** [nhmkdev/cardmaker#150]
## Description of the current issue

Currently, the ElementColor is applied to Images through the ColorMatrix, ImageCache.cs:159-161.  This is done by applying a color bump/translation.  This means that if we want to have colors in a spreadsheet which are then applied to an image, we have to make a flat black image of what is the color, and make an alpha mask over it to let those colors bleed through and still have black/dark regions.  For example:
![image](https://github.com/nhmkdev/cardmaker/assets/1007185/aac9aa11-92ac-4cee-bd4d-c35d997046d7)
![image](https://github.com/nhmkdev/cardmaker/assets/1007185/8fd28074-a74d-43f8-9f8c-88aeaee81157)

This is the only way to have colors ranging from black to the specified color.  It's a huge burden to maintain the images, and also have extra image layers in cards.

## Proposed solution

A more common way to do image combinations/blending is through color multiplication.  This is usually by taking the original pixel color from the image and multiplying it by the value we desire.  For example, using a white image with grading from black/white, then multiplying each pixel by the color matrix using scaling instead of translations, we can use a single image which looks like this:
![image](https://github.com/nhmkdev/cardmaker/assets/1007185/d7289c35-d4ef-41d2-8af1-aa493d7c908e)

The way this is done is by changing the same lines referenced above to use the diagonals of the matrix, instead of the translation positions.  Right now, it's matrix positions 40, 41, 42, when it should really be matrix positions 00, 11, 22.  

```
                        zColor.Matrix00 = (float)colorOverride.R / 255.0f;
                        zColor.Matrix11 = (float)colorOverride.G / 255.0f;
                        zColor.Matrix22 = (float)colorOverride.B / 255.0f;
```

It also becomes necessary to fix the color check on line ImageCache.cs:153, since it's incorrectly comparing against "`Black`".  The proper way to color compare is `(colorOverride.ToArgb() != Color.Black.ToArgb())` because the color comparisons end up checking if "`Black`" is the same name as the colorOverride, which is usually FF000000.  

Changing how this color is applied to an image results in vivid colors and end results which look like:
![image](https://github.com/nhmkdev/cardmaker/assets/1007185/9f6ad1f9-8989-43c3-b965-f69f25ef48f9)

One would be hard pressed to take a black/white image or image set and use the built-in ElementColor in CardMaker to get equivalent results.  This last sample image is an output from CardMaker, taking the suggested greyscale image and merely applying $[elementcolor:ff0000] to it with the other code changes above.

## Stretch Goal

It would also be nice if we could use the ElementColor to handle opacity as well.  Currently at ImageCache.cs:150 the code is `zColor.Matrix33 = (float) zElement.opacity / 255.0f;`  My request would be to have it be replaced with 
```
                zColor.Matrix33 = 
                    ((float) zElement.opacity / 255.0f) * 
                    ((float) colorOverride.A / 255.0f);
```
(Note that `colorOverride.A / 255.0f` is almost always `== 1.0f` as things stand)
This would also mean we should change the if-statement guarding that code to check the colorOverride.A as well.  This means we could have per-element opacity changes encoded in their color, in addition to their opacity.  Special combinations would therefore be possible, especially considering SubLayouts.

## Backward compatibility

Given how difficult it is to use the current method, I imagine FEW FEW FEW users actually use ElementColor in tandem with Graphics/Images. However, in order to maintain backward compatibility, it would make sense to have this be a toggle in the Graphics Settings.  I would suggest it default to "On" since color multiplication is the normal color application taking place in editors such as Photoshop/GIMP, therefore making the functionality feel a lot more natural.  

An alternative to ElementColor could be enabling another attribute for elements called "ColorMatrix" which would override the ElementColor, and allow us to have more complex color methods, such as channel switching, HDR effects, etc.

[Reference on ColorMatrix and how it works](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.imaging.colormatrix?view=dotnet-plat-ext-8.0)

**Comment by MarkVabulas** [comment]
In order for in-line images to work, we also have to add `ImageColor = Color.Black;` to the constructor of `FormattedTextProcessData` since it currently sets the ImageColor to pure transparent blackness.

**Comment by nhmkdev** [comment]
I looked into your suggested change and realized the current and proposed changes are just different use cases. The [original request](https://boardgamegeek.com/thread/2699431/feature-request-colorize-graphic-elements) a few years back was geared towards icons. I have used this feature a lot with graphics downloaded from [the noun project](https://thenounproject.com/icon/checkmark-2193566/) (black icon on transparent image) and it's always worked fine (and been easy 🤣). 

Support for black -> color is something that would definitely be good to have. 👍 

I realize now the limitation of both approaches is that basically they both eliminate the possibility of white or black depending on the approach. For example:
|image description|image|
|--|--|
|original black & white gradient image|![image](https://github.com/nhmkdev/cardmaker/assets/6293880/ced17bbe-a6f8-4b62-abe6-9fe5864d620b)|
|cardmaker current with 0xFF0000FF|![image](https://github.com/nhmkdev/cardmaker/assets/6293880/7fc6e9de-b7d4-4efc-9b16-59a81aa1da9f)|
|cardmaker proposed with 0xFF0000FF|![image](https://github.com/nhmkdev/cardmaker/assets/6293880/e7a119c7-e4e6-4ea2-8046-718107dc4290)|

## Potential Solution
Add a dropdown to the Graphic element to let users pick how to apply the element color to the image.

## Opacity
Supporting opacity via the color you suggested sounds good. I'll double check it doesn't impact anything I know of.

## Color override
Ha good catch with the `(colorOverride.ToArgb() != Color.Black.ToArgb())` 👍 I bet there's a couple spots like that.

**Comment by MarkVabulas** [comment]
So I do acknowledge that they have different use cases, in terms of allowing gradients from black->color, or color->white, that's why I was suggesting somehow allowing access to the entire ColorMatrix.  I'm not sure how that would work, but allowing a specified color to be used as the diagonal or the translation component of the matrix would be the toggles at the moment, though full access to the ColorMatrix would allow for things like swapping Red/Green channels, etc, without having to write code for it.

The issue I really came up to with translation instead of scaling was that hyper-saturation of the channels was possible, where a color starting at 0xAAAAAA, and adding 0xFF0000 to the ElementColor, was giving a color overflow of 0x(FF+AA)AAAA.  This gives incorrect results when you could potentially start with 0x888888, add 0xAA6600, and end up with a completely different color, even though you're just adding grey to a non-grey color.  The assumption wouldn't be to end up with bright yellow when you start with brown...  And that, applied to a gradient, means that you would have a color which could range from brown into bright yellow to white, when you just want shades of brown.  Because of the lack of HDR rendering (since we're limited to 8-bits per color internally), it means that applying non-single-channel colors to an image could give very ugly results.  I'll post an example

**Comment by MarkVabulas** [comment]
Original Gradient, and gradient when color is applied to it in CardMaker currently released
![Gradient](https://github.com/nhmkdev/cardmaker/assets/1007185/f06b4c8f-4879-4616-b454-cc13cc46d238)
![Default copy_001](https://github.com/nhmkdev/cardmaker/assets/1007185/907486dc-ac37-4b0f-8100-c555eb76f022)


The color I'm applying is stated as FFAD03, which is brown.  Compare the color preview with what the middle of the gradient shows:
![image](https://github.com/nhmkdev/cardmaker/assets/1007185/d0497f6c-4cec-45c4-92e2-324ccbae6df9)

**Comment by MarkVabulas** [comment]
Side note:
ImageCache.cs:131 might never return because of the comparison against Color.Black. This reduces the whole point of the ImageCache, right?

**Comment by MarkVabulas** [comment]
I would still love the idea, if the colormatrix ends up being really complex, to have the colormultiplier/coloraddition method.  Maybe ColorMatrix could be a V2 kind of thing.

**Comment by nhmkdev** [comment]
Initial color functionality has been added. 

From my testing:
![cardmaker_color_matrix](https://github.com/nhmkdev/cardmaker/assets/6293880/43f27227-2c8e-4fdf-b730-30082b413e9a)


## Graphic elements
* Now have a new drop down by the color: Add (default/current), Multiply, Matrix
* There's a basic popup to configure the color matrix. 
* **TODO:** In a future submit this will live update as the user edits (preview) like the color selector (at least that's my hope).

## FormattedText elements
* I applied the tweak you suggested (defaulting to `Color.Black`)
* **TODO:** I'll need to add tag(s) to allow control over the color settings.

## Elements
* New fields for color type (int) and color matrix (string)
* Color matrix is a `;` delimited set of 25 floats. This will allow people to easily (🤣) put it in a define/otherwise. This will also let me apply the color matrix as a tag value when I deal with configuring it via FormattedText.

**Comment by nhmkdev** [comment]
Ha yea that bug got me too when I started working on live-editing of the color matrix. 

I'll default to the identity matrix based on https://learn.microsoft.com/en-us/dotnet/api/system.drawing.imaging.colormatrix?view=dotnet-plat-ext-8.0

You can use the inline overrides (and probably the reference overrides too) now: `$[colormatrix:1;0;0;0;0;0;12;0;0;0;0;0;1;0;0;0;0;0;1;0;0;0;0.2;0;1]`  worked for me.

For the color decomposition would you also want a way to get the individual channel values? 
`getRed` `getGreen` `getBlue` `getAlpha`

As I don't mess with graphics stuff a lot... what's the use case where you need decomposition? Is that to build a custom color matrix based on a color's values?

**Comment by nhmkdev** [comment]
2 additional iterations on color type and color matrix:

https://github.com/nhmkdev/cardmaker/commit/9bb2df29399ee882012794340604622018c67019 / https://github.com/nhmkdev/cardmaker/commit/095b3fff5477050de8d7e9f1dd0afbd8b19e60f9

![cardmaker_colormatrix_dialog](https://github.com/nhmkdev/cardmaker/assets/6293880/0ed1cc87-c221-47b8-89af-9cdebaeb18e1)

## Changes
* Live editing of color matrix (when it's valid it will force a redraw)
* Matrix Identity default
* Color matrix undo/redo with 1+ elements selected
* New helper buttons
* Formatted Text tags for setting the color type and color matrix (via string). Need to document them both. Something like this:
  * `<ct=0>...</ct>`
  * `<ct=2><cm=1;0;0;0;0;0;22;0;0;0;0;0;1;0;0;0;0;0;1;0;0;0;0;0;1>...</cm></ct>`
* More tweaks to image cache (maybe bugs?)

The FormattedText aspect needs a lot more testing. I just put in the basic setup.

**Comment by MarkVabulas** [comment]
To answer your question, yes, the purpose of decomposition is to give a user (such as in the spreadsheet) the ability to keep using RGBA hex values, without having to understand how the ColorMatrix works.  Decomposition for individual channels would be great.  Including, potentially, ones that auto-build the color matrix from rgba, based on multiplication or translation.  But that's probably secondary to just having the decomposition.

Usually, in the graphics realm, everything is done with floating point for all channels, always, because of HDR and it simplifies calculations when between 0-1 (and possibly <0.0 or > 1.0) instead of 0-255.

Side note:
After fooling around with the ColorMatrix a little, have you seen how obscenely powerful it is?

**Comment by nhmkdev** [comment]
> After fooling around with the ColorMatrix a little, have you seen how obscenely powerful it is?

👍 I had to look up some examples and I can definitely see how basic functionality is image editors is easily provided (invert, greyscale, and all the others!).

**Comment by MarkVabulas** [comment]
I think that a conversion into just 4 values is useful, because sticking that into a color matrix we can always append a `;0.0` to the end, i.e. `@[decomposition,@[color]];0.0`

**Comment by nhmkdev** [comment]
New functions added for Color Normalized Values:

`#cnv;[color format string]#`

`cnv, cnvargb, cnvrgba, cnva, cnvr, cnvg, cnvb`

Technically works with all supported color string format (including named).

I'm going to mark this as completed.
