### ISSUE TITLE
Bold and italicized text seemingly not aligning with the font's bold/italicized version

### ISSUE THREAD

**Issue by wholton** [nhmkdev/cardmaker#152]
**Describe the bug**
I have a word that is both bold and italicized. When I use the font I've set that word to in a different program, it looks different (and correct, compared to what I expect). In this program, it generates more slanted.

The font is Myriad Pro Bold Italic, defined as: `<f=Myriad Pro;50><b><i>ACTION:</i></b></f>`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version CardMaker 1.4.0.0 A2

**Screenshots**
Cardmaker output:
![Cardmaker output](https://github.com/nhmkdev/cardmaker/assets/3317595/984ace67-cfaa-4dac-b4f9-ca0f469fb043)
Expected:
![Expected](https://github.com/nhmkdev/cardmaker/assets/3317595/8e65cedd-d3f2-47d9-8d3b-4bceeb6f2391)
Comparison - overlapped with opacity at 50%:
![Comparison - overlapped with opacity at 50%](https://github.com/nhmkdev/cardmaker/assets/3317595/6901f9b8-082e-4e22-a861-667a8cf0f9c8)

**Comment by wholton** [comment]
![image](https://github.com/nhmkdev/cardmaker/assets/3317595/f0dd6f35-7a47-45ba-957e-2e87b666950b)

**Comment by nhmkdev** [comment]
I attempted to reproduce the issue based on your setup:
1. Downloaded the `Myriad Pro` font family from Adobe
2. Setup a Libre Office Writer doc with a 72pt "ACTION:" text (bold+italic) -- this looks like your word doc result
3. Created a Text and FormattedText element (all using Myriad Pro with bold+italic)
    1. Text set to "ACTION:"
    2. Formatted Text Set to: `ACTION:<br><f=Myriad Pro;72><b><i>ACTION:</i></b></f>` (and some line spacing tweaks)
    3. Result pictured below

![cardmaker_action_myriad_pro](https://github.com/nhmkdev/cardmaker/assets/6293880/78fd647b-c93d-4f7d-85e2-bdb627ace949)

Is the Font you have selected in CardMaker called `Myriad Pro Bold Italic` ? Maybe it's attempting to assign italics to an already italicized font?

**Comment by wholton** [comment]
Okay, you sent me down a path to finding it. I had a Myriad Pro Bold Italic _Semicondensed_ font that was installed. After uninstalling that, it seems to have resolved.

**Comment by wholton** [comment]
![image](https://github.com/nhmkdev/cardmaker/assets/3317595/c11c0d66-ad8f-4cb0-8907-92dd6e47facf)
