### ISSUE TITLE
FormattedText is generated without proper spacing

### ISSUE THREAD

**Issue by wholton** [nhmkdev/cardmaker#153]
**Describe the bug**
The generated text for Myriad Pro Light Bold Italic has weird spacing. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version CardMaker 1.4.0.0 A2

**Screenshots**
![image](https://github.com/nhmkdev/cardmaker/assets/3317595/efd6996b-054f-4f1e-a4b0-ed37509e1be0)

**Comment by nhmkdev** [comment]
I was unable to reproduce exactly the same problem with the `Access denied` turning into `Accessdenied` (mashed together almost).

Couple of thoughts:
* What is the `@[HR,1]` doing? (or does it play no role?)
* When viewing the FormattedText in CardMaker are you at 1.00 zoom? Anything other than 1.00 zoom can look a little funny as the .NET renderer can run into imperfections.
* What type of reference are you using? Maybe there's a bug with the quotes in that field or something strange.
* One hack you can use is the push tag-- Example: `Access<push=20>denied`

**Comment by wholton** [comment]
1. HR is adding an image -- the horizontal line above the "ACCESS" text.
2. Here it is on 1.00. It does look a bit better, though a little close still. Also changed the quotes to standard " and it's the same.
![image](https://github.com/nhmkdev/cardmaker/assets/3317595/3fa83dee-2634-415d-a055-a566091cc573)
3. This is what it's referencing:
![image](https://github.com/nhmkdev/cardmaker/assets/3317595/69346774-c97d-4f8c-b14c-7bceca589ff3)

**Comment by MarkVabulas** [comment]
@[HR] is just a shortcut to include an inline image with a standard size:
`HR,<br><br><ac><img=Images\Symbol_HR.png#(if {1} != #empty then ;{1};{1})#></ac><br>`

**Comment by nhmkdev** [comment]
I'm going to be considering/testing an alternative approach to measuring text that may help. Not sure if it will work out though!

**Comment by nhmkdev** [comment]
In the new alpha release you can change the measure method.
Change this via `Tools > Settings... > String Measure Method` (MeasureStringGenericTypoGraphic is the new one)

https://github.com/nhmkdev/cardmaker/releases/tag/v.1.4.0.0-unstable.v.a3

I am a little concerned because I was never able reproduce the really bad spacing you were seeing but this should look a bit better.

**Comment by wholton** [comment]
![image](https://github.com/nhmkdev/cardmaker/assets/3317595/8a0a92f5-16e2-42c2-9ed0-37ac1bdc889d)
Nice! Thanks for that!
