### ISSUE TITLE
[Feature Request] Insert and Duplicate in place

### ISSUE THREAD

**Issue by Blkx-Darkreaper** [nhmkdev/cardmaker#157]
It would be helpful if when creating new elements or duplicating elements if they could be inserted just above or below the currently selected element so the layer order of most of the project doesn't need to be updated. When there are a lot of layers moving a new group of layers up to the top can be time consuming and makes the application unresponsive until it's completed

**Comment by nhmkdev** [comment]
The basic implementation allowing the user to specify where to add an element will be included in the next release (probably v.1.4.0.0-unstable.v.a5). The create/duplicate dialog will include a drop down with 4 options for where to add the new element(s): top, bottom, above, and below. Above and below being relative to the currently selected item.

I'd also like to look into drag-drop for the elements in the list.

**Comment by nhmkdev** [comment]
For dupe and create there is now a dropdown to specify the destination of the new elements: https://github.com/nhmkdev/cardmaker/releases/tag/v.1.4.0.0-unstable.v.a5 (though that version needs a lot more testing!).

I'll keep this ticket open as I want to consider the same for paste (and more?).

**Comment by nhmkdev** [comment]
overhaul submitted (and hopefully with limited bugs) making add/dupe/paste use the same logic to put new elements in-place based on the selected item(s).
