### ISSUE TITLE
[Feature Request] Translate menu option

### ISSUE THREAD

**Issue by Blkx-Darkreaper** [nhmkdev/cardmaker#158]
Add option to the Edit menu dropdown to translate all selected elements. This would bring up a dialog box to translate the x and y positions of the selected elements. Hitting ok would then apply the translations, adding or subtracting the x and y values from each element's x and y position

This would allow you to shift selected sections by a certain amount while preserving their relative positions to each other

**Comment by nhmkdev** [comment]
Sure that makes sense. A more precise move than just multi-selecting elements and dragging them. 👍

**Comment by nhmkdev** [comment]
New "Move" button added to the Layout Control (by scale, resize, and the others): https://github.com/nhmkdev/cardmaker/releases/tag/v.1.4.0.0-unstable.v.a5 (though that version needs a lot more testing!).
