### ISSUE TITLE
[Request] Alignment options

### ISSUE THREAD

**Issue by ericraue** [nhmkdev/cardmaker#16]
A common use case is centering an element horizontally or vertically in the layout. It would be handy to have a buttons that do this. Another use case is evenly spacing objects.

See [InDesign's alignment options](http://design.tutsplus.com/tutorials/quick-tip-how-to-use-the-align-panel-in-adobe-indesign--vector-7088) for ideas.

**Comment by nhmkdev** [comment]
I implemented a first pass at this in this release: https://github.com/nhmkdev/cardmaker/releases/tag/v.0.99.3.0-unstable.v.a2

Let me know if there's anything busted or if you have any specific requests. I am thinking about expanding the alignment options for the custom horizontal and custom vertical buttons to allow for near and far alignment is association with the "first element" (that statement will probably make more sense after you try it out).

I also have not documented the functionality in the manual at all.

**Comment by nhmkdev** [comment]
Ha I just realized I have all the alignment names backwards... will fix that.

**Comment by nhmkdev** [comment]
The initial version of this will be included in version 0.99.3.0 (pre-releases available now)
