### ISSUE TITLE
Feature Request: Expose text measurement function to translator

### ISSUE THREAD

**Issue by salmelo** [nhmkdev/cardmaker#161]
Working on a project with a background element that changes size (using one of two different image files) depending on the text it's supposed to be surrounding, which is currently difficult to express without manually selecting it for every card.

Ideally I'd like to be able to pick the image automatically based on the size of the text in question, but that's not currently possible as far as I can tell. The closest I can get is using the javascript translator to count the characters and base the decision on that.

**Comment by nhmkdev** [comment]
Is it fair to assume that the text you want to measure is always on 1 line? Or are you looking for the height of the text?

**Comment by salmelo** [comment]
In this particular instance the intent is to keep it on one line, so yea only horizontal measurement would be needed. I'm sure vertical measurement could be handy too but I don't know how much harder that is.

**Comment by nhmkdev** [comment]
Rough version has been submitted with zero instructions 🤣 -- https://github.com/nhmkdev/cardmaker/commit/d194332c192a6fc5271283d564d0f3d8d7d25d6f?diff=unified

* Currently only available if you're using the Incept translator (not JS) -- guessing you wanted it in JS?
* Usage: `#strw[Arial;27;0;0;0;0]measure this#` will result in the numeric width of "measure this" with the font specified in the brackets.

**Comment by salmelo** [comment]
It would definitely be preferable if it was available in both. :)
I imagine the method sharing groundwork I in for override fields would help for getting this into JS as well?

**Comment by nhmkdev** [comment]
Merged in a quick hack to expose the method in JavaScript:

`MeasureStringWidth('Arial;36;0;0;0;0', 'sample text');`

It should return a number. I need to look into making all the fields on the element available (if they aren't already). I almost never use the JavaScript functionality in CardMaker (and very few people ever ask about it!).

**Comment by salmelo** [comment]
I was just looking to see if I could throw it together real quick myself and you beat me to it, pretty much wrote exactly the same function I was too.

**Comment by salmelo** [comment]
Did a quick test replacing my existing string length check with this and it works perfectly. 👍

**Comment by nhmkdev** [comment]
I'll be updating the docs with information. Closing this out.
