### ISSUE TITLE
VS2022 Fails to run tests

### ISSUE THREAD

**Issue by salmelo** [nhmkdev/cardmaker#165]
Test explorer will show all the tests, but when trying to run nothing happens and you get "Test run aborted" no matter what you do.

I've solved it locally by adding a reference to nuget package [NUnit3TestAdapter](https://www.nuget.org/packages/NUnit3TestAdapter/4.6.0?_src=template)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.3+ (not tested earlier)

**Screenshots**
![image](https://github.com/user-attachments/assets/bbedb169-ed73-4e3e-891f-84226e2feba0)

**Comment by nhmkdev** [comment]
I always use resharper and it has better handling for tests apparently (or obfuscates issues 🤣 ).

I switched over to the standard unit test runner in VS2022 and hit the issues you are. I added `NUnit3TestAdapter` and still ran into some issues. I had to add clearscript to the unit test project (and finally removed some old copy commands from the project too). I'll push up the changes in a bit.

**Comment by nhmkdev** [comment]
https://github.com/nhmkdev/cardmaker/commit/df9f86c9d481ede9eec89348241b4520087235fd

**Comment by nhmkdev** [comment]
Let me know if this still running into trouble with the latest.

**Comment by salmelo** [comment]
So far so good. 👍
