### ISSUE TITLE
[Request] Add addional layout features

### ISSUE THREAD

**Issue by daniel--** [nhmkdev/cardmaker#20]
I would love to have additional features for controlling the placement of Elements. In particular I would love to have something like [qt layouts](http://doc.qt.io/qt-4.8/designer-layouts.html). The ability to group elements together and manipulating them easily as a group would be very useful. The current 'custom align elements' is a start but lacks the persistence and grid functionality offerers by layout elements. Thanks for your great work.

**Comment by nhmkdev** [comment]
Over the years I have also found a need for the Photoshop-like group functionality. One problem with the layouts concept is that it would treat each child element as its own entity. Often times I create a collection of elements that I really want treated as a single element (one example would be text element on top of an ellipse shape element). The layout would then separate these elements and align them accordingly (incorrectly).

Is Grid the only layout type you can't achieve with the "custom align elements" or are there others you might find useful?

I like the idea but need to think of a good solution to avoid the problem I described.

Thanks for the suggestion!

**Comment by daniel--** [comment]
Grid is the type that initially put the thought in my mind, but even having a permanent grouping could be helpful in cases that 'custom align elements' does cover. I can't think of any other layouts off the top of my head but your overlapping elements case seems useful.

A solution could be to allow elements to be assigned to a cell in the grid, and if multiple elements are assigned then they overlap, this would solve your use case using a 1x1 grid. Not sure how to display this in the ui though. Maybe, make the Layout control a tree list.

Perhaps I will get around to learning c# and start contributing.

**Comment by nhmkdev** [comment]
Closing out old bugs/issues.
