### ISSUE TITLE
[Bug] Doesn't respect high dpi settings on linux mint cinnamin

### ISSUE THREAD

**Issue by daniel--** [nhmkdev/cardmaker#22]
Thanks for fixing those other Mono bugs. Thought I would let you know about another I recently found although this one may not be worth fixing as there is an easy work around.

When running linux mint in high dpi mode the fonts used in card layouts are doubled but nothing else is, resulting in text appearing larger then expected when using files created on systems without high dpi set.

**Comment by nhmkdev** [comment]
Closing out old bugs/issues.
