### ISSUE TITLE
[PERSONAL] Reference File Unable to Connect

### ISSUE THREAD

**Issue by dwolffnicolucci** [nhmkdev/cardmaker#24]
Hello!

I found this program and was very excited to use it but I can't seem to get the reference file to work in any capacity. I've tried saving the CSV from multiple programs and I just don't understand what's not working.

I even tried the test one supplied and every time it says [bad name] and I'm unclear what I'm doing wrong. Is there something I need to do before the file is put in? Do I need to change the count? I really want to use this program as its the only one that fits my needs but I just can't seem to get this to work.

I also have no programming knowledge which is why I'm using this not NanDeck.

Thank you so much!

**Comment by nhmkdev** [comment]
Are you able to load the included sample project and see the associated reference files/values working?

Did you run into any issues adding a reference file to your layout(s)? (any error messages?)

When you have an element selected does the list view in the Element window show your columns/values? Can you right-click an entry in the list view and select "Add reference to [your column]..." and have the text appear correctly?

Which version of CardMaker are you running? Which OS are you running?

**Comment by dwolffnicolucci** [comment]
It doesn't populate the layout or element area with any reference. The default thing highlights green but that's it. I'm running Microsoft 10, the version that's currently on the download page I don't have exact reference." Number.

When I right click on default under layout and refer nice csv it doesn't populate. I feel like I'm just probably missing one key step but it's such a simple process I don't know what it is. Sorry for the dumb question I just really want to start using your program!

**Comment by nhmkdev** [comment]
You may want to try the Layout Menu option "Reload References" just to force the application to load the reference (shortcut key is F9). Be sure the Layout in the Project window is selected too (I doubt this is the issue but just in case). Also I'm assuming you already have a Text Element referencing a column in your csv file via **@[column_name]** (very likely since you mentioned the "bad name")

There does appear to be a bug where the reference is not immediately active so I'll check into that too. Hitting F9 worked in my case.

Hopefully that's the issue!

**Comment by dwolffnicolucci** [comment]
It worked forcing a reload! Thank you. Seems obvious now but its awesome, worked perfectly. Just had to kick it to recognize it basically.

Excited to start working on my game now, thank you so much for a great program! It's perfect for prototyping it's awesome.

**Comment by nhmkdev** [comment]
Great! Thanks for raising the issue. 

The latest unstable build has a fix for this if you happen to be running the unstable version(s). [v.0.99.4.0-unstable.v.a8](https://github.com/nhmkdev/cardmaker/releases/tag/v.0.99.4.0-unstable.v.a8)
