### ISSUE TITLE
Add anchor for elements

### ISSUE THREAD

**Issue by Papiertig0r** [nhmkdev/cardmaker#30]
As I see it, the anchor point for every element is on its lower left corner which makes it difficult to arrange elements on the right edge of cards.

**Comment by nhmkdev** [comment]
Hmm, what difficulty are you having arranging elements on the right edge of cards?

The anchor point is the upper left for elements (for better or for worse) and any rotations are performed at the center of the element.

**Comment by nhmkdev** [comment]
Closing out old bugs/issues.
