### ISSUE TITLE
Add color option to shape elements

### ISSUE THREAD

**Issue by Papiertig0r** [nhmkdev/cardmaker#31]
It would be nice to have a color option for shapes, so you could do
`#rect;600;600;90;@[color]#`

**Comment by nhmkdev** [comment]
This could definitely be a useful/optional setting on a shape. Are you using the element override functionality to do this now?

**Comment by virtualflesh** [comment]
I agree this would be a useful option. Perhaps extend the idea towards a general implementation. If @[override:...] was interpretable in any element "Definition", then one could universally programmatically set an element's attributes.
An element with name "typecolorback" is created in Card Maker. To change its color dynamically, a, example CSV file contains:
```
type,override:TypeColorBack:elementcolor
type_1,@[color_@[type]]
type_2,@[color_@[type]]
```

a DEFINES.CSV file contains:
```
Define,Value
color_type1,128255128
color_type2,010000050

```

This works, but the CSV column containing "@[color_@[type]]" is tediously repeated. An attribute override in the element's Definition within Card Maker would streamline this. There is an override control conflict, but I would guess the CSV file override could take precedence over the element Definition override.

**Comment by nhmkdev** [comment]
You can now override within the definition field (new functionality so beware): https://github.com/nhmkdev/cardmaker/releases/tag/v.1.0.0.1-unstable.v.a3
