### ISSUE TITLE
Any plan to make this more portable?

### ISSUE THREAD

**Issue by arnauldvm** [nhmkdev/cardmaker#40]
Unfortunately C# bounds this to a single platform.
Do you have any intention to port this to a more portable language?

**Comment by nhmkdev** [comment]
I have definitely considered it. The limitations I ran into just trying to make the application run with Mono on Ubuntu made it obvious that the risk of losing (or having to recreate) a lot of functionality is high. It does work in Mono but it really should be in another more portable language to better serve non-Windows operating systems.

At this time I do not have any specific plans. Though I am curious to know what kinds of cross platform windowing/graphics rendering libraries could make the process easier.

**Comment by arnauldvm** [comment]
These days there are two major cross-platform technologies:
 - Java based (quite outdated as far as front-end development is concerned, and it's not browser friendly anymore)
 - JavaScript based (browser friendly, and hypest)

(There are other technologies, but less widely used.)

If someone would need to start from scratch, I would definitely recommend to go for a JS based stack.

Useful readings: [Electron](https://www.wired.com/2016/05/javascript-conquered-web-now-taking-desktop/), [Progressive Web Apps](https://developers.google.com/web/progressive-web-apps/
), [Google Drive APIs](https://developers.google.com/drive/)

**Comment by nhmkdev** [comment]
Closing out old bugs/issues.
