### ISSUE TITLE
[Bug] some charactere can't be show

### ISSUE THREAD

**Issue by leroipanda** [nhmkdev/cardmaker#47]
when i use character like (é,à,ù) in my referenve file (csv) ;they doesnt appear on a text and a formatted text

**Comment by nhmkdev** [comment]
Have you tried saving the CSV file as UTF-8 as described here: https://github.com/nhmkdev/cardmaker/wiki/user-utf8

**Comment by nhmkdev** [comment]
I am going to close this out. If this is still not functional please re-open it.
