### ISSUE TITLE
.exe

### ISSUE THREAD

**Issue by genevajoy** [nhmkdev/cardmaker#48]
I can't find the program file. Is there something I don't understand. I downloaded it but I can't find the file i am supposed to run?

**Comment by nhmkdev** [comment]
You might have downloaded the source code.

See the Download section in 
https://github.com/nhmkdev/cardmaker/releases/tag/v.1.0.0.0
OR 
https://github.com/nhmkdev/cardmaker/releases (if you want the latest and less-tested version)

**Comment by genevajoy** [comment]
Thank you! I was on the wrong page lol. 
Thank you
Geneva
