### ISSUE TITLE
![cardcount] export error with multiple layouts

### ISSUE THREAD

**Issue by virtualflesh** [nhmkdev/cardmaker#49]
For a project with multiple layouts, when exporting to PDF or saving images, the ![cardcount] value for all layouts is  equal to the ![cardcount] of the bottom-most layout. The bottom-most layout means the layout shown at the bottom of the Project window.

**Comment by nhmkdev** [comment]
Thanks for the information! I was able to easily find the issue. I'll have to see how easy the fix will be...

**Comment by nhmkdev** [comment]
I'll put the fix in the next alpha build I make. Let me know if you need this soon... otherwise I won't rush to make a new release.

**Comment by virtualflesh** [comment]
No rush. Thanks for this tool. It's awesome.

**Comment by nhmkdev** [comment]
Should be fixed with https://github.com/nhmkdev/cardmaker/releases/tag/v.1.0.0.2-unstable.v.a1

Please let me know if not.
