### ISSUE TITLE
[Request] Support manipulation of rotated Elements in the canvas

### ISSUE THREAD

**Issue by nhmkdev** [nhmkdev/cardmaker#5]
1. The render box for Elements should display the final rotated bounds of a rotated Element (easy!)
2. The mouse scale/resize functions should operate on rotated Elements (tough!)

Note: I did some research experiments on this and there is a lot of complexity due to the current functionality that rotates around the center of an element. Even when changed to rotate from the upper left corner there are complications. One major issue is that Elements are defined by a Rectangle (x, y, width, height), not 4 discrete points. The solution may well involve converting the Rectangle to 4 discrete points and then translating the final resulting points back into a Rectangle. 

If someone loves a good challenge with trigonometry this is your opportunity! I may attempt to tackle this again when I am feeling more patient.

**Comment by nhmkdev** [comment]
Will the rectangle size change or are you concerned it might? To determine the x,y of the element you would need to rotate the point 562,0 around the center of your image in the desired rotated position (-90 degrees so you get the element position). That does not sounds like fun... I am guessing that manually adjusting the element to appear where you expect is a bit less precise than you would like...

**Comment by jmb496** [comment]
The rectangle size will be unchanged in most cases I think.  I'm planning to print these on real cards, so I'd like it to be precise.  I'll just use this as an excuse to shake off my programming rust and write a python script to convert the xml.  This is good for me. :)

Also, thanks for all your work on CardMaker.  It's allowed me to make some very cool projects.

**Comment by nhmkdev** [comment]
Closing out old bugs/issues.
