### ISSUE TITLE
Exported image or PDF can differ from the CardMaker Canvas WYSIWYG for FormattedText Element

### ISSUE THREAD

**Issue by virtualflesh** [nhmkdev/cardmaker#50]
WYSIWYG vs Export snapshots:
![example_bug_image](https://user-images.githubusercontent.com/30025028/33517816-f8d4cbf4-d747-11e7-8527-3994c522bea2.png)

The CMP file (appended txt extension to conform to github upload constraints) exhibiting:
[example_bug.cmp.txt](https://github.com/nhmkdev/cardmaker/files/1523974/example_bug.cmp.txt)

**Comment by nhmkdev** [comment]
I have noticed that if you are zoomed at anything other that 1.0 you _**might**_ run into this. I loaded the project locally (luckily I have the font). I exported to image and compared with what I am seeing in the UI and they matched up (with your right-side export image).

What zoom level are you at for the CardMaker WYSIWYG images?

I blame zoom, which in turn might be my fault. :P

**Comment by virtualflesh** [comment]
Zoom level 0.5 and 0.75 exhibit the error. On the zoom function, is there a quick way to change the zoom level to "fit" the max image boundary?

**Comment by nhmkdev** [comment]
There is nothing other than manually setting the zoom size. 

Just to confirm, you would like to be able to have a button to set the zoom value so that the canvas window is filled (or something else?).

**Comment by virtualflesh** [comment]
Ya. something like that. I work at 400 dpi and the canvas window defaults to 1.0, so I reset the canvas window to 0.65 for my card creations. Would be cool if after zooming in for some fine detailed work, I could "click" so the layout consumes the canvas. Not sure I;m using the right terms, but to fill the currently sized canvas window to "best fit" or the like could be convenient. I personally don't mind the way it is. I'm simply interested in efficient working so I look for ways to use (or make) my tools of choice as effective as they can be.

**Comment by nhmkdev** [comment]
Closing out old bugs/issues.
