### ISSUE TITLE
[Request] When using Export Project skip layouts with a reference but no data

### ISSUE THREAD

**Issue by ericraue** [nhmkdev/cardmaker#53]
I have a CardMaker project with multiple card layouts. Usually I'm only exporting the changes to print and this means some layouts might contain no data. When exporting the project this results in generating a single card for each layout that contains no data.

If the changes were limited to a single layout I could simply export the layout, however, my changes often cover multiple layouts but not all.

I would like to request CardMaker skips layouts with a reference (so those not using a reference are unaffected) while exporting the project to images/PDF.

**Comment by nhmkdev** [comment]
Ah that's a good use case. I'll detect the following and skip:
- Layouts with a references where there are simply no entries (all 0 count).

Not sure how easy the change will be... I hope it is! I know I do some funny things to default to the 1 card entry you are seeing.

**Comment by nhmkdev** [comment]
Here's a release with the functionality (super lightly tested): https://github.com/nhmkdev/cardmaker/releases/tag/v.1.0.0.2-unstable.v.a8

**Comment by ericraue** [comment]
That was quick thanks! It's working great with my project setup [as detailed here](https://boardgamegeek.com/thread/1965269/method-using-single-spreadsheet-multiple-card-layo). I'll continue to test this version and let you know if there are issues.
