### ISSUE TITLE
preserve transparency in png export

### ISSUE THREAD

**Issue by jpraet** [nhmkdev/cardmaker#54]
When exporting a card layout as png, you currently get a white background for transparent parts of the card. It would be nice if there was an option to preserve the transparency.

My use case for this is that I want to create cards for a digital prototype in tabletopia and I would like these cards to have rounded corners.

**Comment by nhmkdev** [comment]
There are export settings on each layout (right-click and select Configure Layout Settings). One of them lets you export the background as transparent. Let me know if that doesn't work for you.

**Comment by jpraet** [comment]
Yup, that works. My bad, thanks!
