### ISSUE TITLE
[Request] Command line export / functionality

### ISSUE THREAD

**Issue by nhmkdev** [nhmkdev/cardmaker#6]
Support some form of command line export that skips opening the UI completely. There are a number of things currently blocking this that rely too heavily on forms. This kind of functionality should be moved into classes so it is possible to differentiate between a command line activity and a winform activity. One example of such a section is the Deck loading that uses a Wait dialog. Deck loading should be broken into winform vs. not. This should also makesthe creation of unit tests a bit easier.

Possible Example: CardMaker -p (path to project) -images=png

This is not a high priority item.

**Comment by ericraue** [comment]
Not sure how many people would use this. CardMaker is primarily for prototyping. If this was implemented it should support PDF export and Google references.

**Comment by nhmkdev** [comment]
You're correct that most people (all people?) will just use this for prototyping board game components.

I like to think of CardMaker outside of the context of board games. Someone could be generating business cards, video game graphics, or web page icons. I recall working with video game artists that were very happy to run a batch file to execute an automated process versus having to manually open yet another application, run through a number of dialogs, and click save to generate new data.

**Comment by darrenswhite** [comment]
Command line support would be great!

**Comment by jpraet** [comment]
Yes, I would also be very interested in having a command line tool to export the cards to images or PDF.

**Comment by virtualflesh** [comment]
Copy of comment from issue #74 : This is totally an enhancement, but I noticed in the application's TODO section the idea for a command-line export is noted. This is an excellent idea! If you need anyone to help you test it, I'll go up to bat first.

**Comment by virtualflesh** [comment]
I strongly support this feature as it enables automating card production with minor tweaks to content.

**Comment by xetra11** [comment]
Need!

**Comment by nhmkdev** [comment]
One challenge anyone will face with automation of anything involving google sheets is how to get the token for the app. Obviously you don't want the application launching a browser like it normally does... and manually entering it. Some kind of simple app or script could probably trigger the process to extract it for use with the CardMaker command line.

**Comment by nhmkdev** [comment]
Work in progress but an example (working/local) export to pdf:

`CardMaker -projectPath E:\CardMaker\bin\Release\sample\sample_project.cmp -exportFormat pdf -exportPath "E:\!work\!export\file.pdf"`

**Comment by ericraue** [comment]
> One challenge anyone will face with automation of anything involving google sheets is how to get the token for the app.

Have you looked into using [Publish to Web](https://support.google.com/a/users/answer/9308870?hl=en) to download the entire spreadsheet as a xlsx file or link to individual .csv files? No Google credentials required and the link is private.

**Comment by nhmkdev** [comment]
Highly experimental version: [1.1.0.0.A11](https://github.com/nhmkdev/cardmaker/releases/tag/v.1.1.0.0-unstable.v.a11)  -- you'll notice the console window hanging around if you load the normal UI (that will go away in some version...). I still have plenty to improve but I wanted to get my primary changes into github and out of my brain.

The instructions for the command line can be found at the end of the main pdf.

The changes were monstrous as the progress reporting (the wait dialog) was very tied to the main application form.

@virtualflesh you volunteered to try it out! (brave soul)

**Comment by virtualflesh** [comment]
> Highly experimental version: [1.1.0.0.A11](https://github.com/nhmkdev/cardmaker/releases/tag/v.1.1.0.0-unstable.v.a11) -- you'll notice the console window hanging around if you load the normal UI (that will go away in some version...). I still have plenty to improve but I wanted to get my primary changes into github and out of my brain.
> 
> The instructions for the command line can be found at the end of the main pdf.
> 
> The changes were monstrous as the progress reporting (the wait dialog) was very tied to the main application form.
> 
> @virtualflesh you volunteered to try it out! (brave soul)

It's a brave new world. The command line produced images that match exactly what is shown in the GUI. It is also simple, fast, and informative. No crashes. The text-based progress bars look good and they work.

There are... other problems... GUI Log messages contaminate the console a bit. Things like "22:01:56.72::Newline found in formatted text input. This is a bug! Report it!". I intentionally have newlines in the text. It works well though it is indicating an error. Also the defines window is blank and some of the images that work in 1.0.0.2 do not load and appear to corrupt other element's brackets. After image generation there were console messages like "No defines found for reference: <filename>,csv". Likely related to the blank defines window? Interesting thing is that the defines did load and were present in the produced images.

Keep it up, dude!

**Comment by nhmkdev** [comment]
> There are... other problems... GUI Log messages contaminate the console a bit. Things like "22:01:56.72::Newline found in formatted text input. This is a bug! Report it!". I intentionally have newlines in the text. It works well though it is indicating an error. Also the defines window is blank and some of the images that work in 1.0.0.2 do not load and appear to corrupt other element's brackets. After image generation there were console messages like "No defines found for reference: ,csv". Likely related to the blank defines window? Interesting thing is that the defines did load and were present in the produced images.

Thanks for checking it out! The loading of references was heavily impacted by changes to how progress is reported/tracked (now that I have to support more than one approach). I'll check into the ones you described. I think I saw the image issue too at some point ... but just ignored it 👎  (haha)

**Comment by nhmkdev** [comment]
[1.1.0.0.A11](https://github.com/nhmkdev/cardmaker/releases/tag/v.1.1.0.0-unstable.v.a11) -- updated with the fix for the defines loading issue (at least one of the ones I saw). The title of the app will indicate A11-1 as the version (not just A11). Also the console window will auto-hide if the UI loads up.

**Comment by xetra11** [comment]
Uh thrilling - will try it out asap!

**Comment by nhmkdev** [comment]
First draft of this is in 1.1.x.
