### ISSUE TITLE
Could this app generate high resolution cards for mobile apps?

### ISSUE THREAD

**Issue by elieobeid7** [nhmkdev/cardmaker#67]
If so what settings are best for mobile apps, I want to generate poker cards, I see in the example that you've referenced how to do that but I'm not sure if you meant for mobile or not.

**Comment by nhmkdev** [comment]
You could definitely generate high resolution cards with it. The poker cards described [here](https://github.com/nhmkdev/cardmaker/wiki/user) are intended for print but if needed to target a specific DPI for mobile development you could adjust accordingly. I would always suggest making things high DPI and scaling down accordingly.

**Comment by elieobeid7** [comment]
thank you for your reply/
