### ISSUE TITLE
[Request] ISO-8859-1 and the CSV file

### ISSUE THREAD

**Issue by brunogsa** [nhmkdev/cardmaker#7]
Hey there!
I'd like to thank you for this great tool and sorry if I missed something before coming here.

I've tried to add some text to my cards, but found these "???" instead of my special characters.
I've attached some screenshots for a better understanding.

If I try to write these special characters directly in the element, they're shown correctly.
But, when I try to add the same text, coming from a CSV reference, the issue occurs.

Are you intending to support ISO-8859-1?
Is it a bug?

Thanks in advance!

![iso-8859-1-issue-2-card-maker](https://cloud.githubusercontent.com/assets/4551005/9431741/e270db26-49ed-11e5-9f3d-a43484a84325.png)

![iso-8859-1-issue-card-maker](https://cloud.githubusercontent.com/assets/4551005/9431742/e276c180-49ed-11e5-82cd-2b50532d0441.png)

**Comment by nhmkdev** [comment]
Someone else ran into a similar problem and there may be a solution [documented here](https://www.boardgamegeek.com/thread/1361990/accents-and-other-characters). Can you try out that solution and see if it works?

The quick test is to open and re-save your CSV with notepad. Notepad in windows can add the mark by selecting save as and choosing UTF-8 Encoding. Many programs drop the special byte-order mark. 

I hope that works for you. If not please let me know.

**Comment by brunogsa** [comment]
I've just did what you said and it worked like a charm.
OpenOffice can be used for editing CSV as well, but people must pay attention in the encoding, which must be "Unicode (UTF-8)".

Thanks you very much!

![resolved-1](https://cloud.githubusercontent.com/assets/4551005/9432416/f1fa3320-49f8-11e5-8cbe-fa6872501b8f.png)

![resolved-2](https://cloud.githubusercontent.com/assets/4551005/9432417/f1fdb5a4-49f8-11e5-8434-92583fac61e3.png)

![resolved-3](https://cloud.githubusercontent.com/assets/4551005/9432418/f2009f80-49f8-11e5-93ff-a1e068725203.png)

**Comment by nhmkdev** [comment]
Great! I'm glad it worked for you.
