### ISSUE TITLE
Support repeat for images and shapes

### ISSUE THREAD

**Issue by aethy** [nhmkdev/cardmaker#70]
Feature request: please support repetition of shapes and images, e.g.:

`#repeat;@[nb of repetitions];@[image]#` (together with "graphic")
`#(repeat;5;#(ellipse;0;70;70)#)#` (together with "shape")

**Comment by nhmkdev** [comment]
I could see adding support for inline shapes in FormattedText.

There's already a way to repeat graphics in FormattedText too:
`#repeat;3;<img=images-color/noun_User_2197571.png>#`

**Comment by nhmkdev** [comment]
Closing out old bugs/issues. Will create a new enhancement for FormattedText shapes.
