### ISSUE TITLE
Command-line export

### ISSUE THREAD

**Issue by virtualflesh** [nhmkdev/cardmaker#74]
This is totally an enhancement, but I noticed in the application's TODO section the idea for a command-line export is noted. This is an excellent idea! If you need anyone to help you test it, I'll go up to bat first.

**Comment by xetra11** [comment]
I'd love the idea as well! This way I could make a webapp that listens to changes in my Google Sheets and directly exports the newly created cards!

**Comment by nhmkdev** [comment]
https://github.com/nhmkdev/cardmaker/issues/6 << existing issue. If you want to move any comments over there I will close this one out.

I'll put this on my list as the next thing to tackle. I tried a super simple prototype of the changes and it went reasonably well. There's still plenty to work out of course...

**Comment by nhmkdev** [comment]
Closing out as a dupe.
