### ISSUE TITLE
Exception thrown and application termination if image asset externally writing

### ISSUE THREAD

**Issue by virtualflesh** [nhmkdev/cardmaker#75]
While simultaneously 1) saving to disk an image asset referenced by a CardMaker "Graphic" element type, and 2) using CardMaker's "Clear Image Cache", the application terminated ungracefully.

**Comment by nhmkdev** [comment]
To be super clear the external app had not finished saving the image and you clicked clear image cache?

Or was it after the external app finished saving and you tried to get CardMaker to reload the changes?

**Comment by virtualflesh** [comment]
correct, the termination occurs only when the external app had not finished saving.

**Comment by nhmkdev** [comment]
Closing out old bugs/issues.
