### ISSUE TITLE
Can't paste into Color HexCode for TextColors

### ISSUE THREAD

**Issue by xetra11** [nhmkdev/cardmaker#77]
Unfortunately I am not able to paste anything in here.

![image](https://user-images.githubusercontent.com/8149023/78811145-b331e380-79c9-11ea-925f-5a48a0cf01bd.png)

**Comment by nhmkdev** [comment]
I could add that in. If you paste or type anything in (assuming it's valid) it could adjust the color numeric boxes.

**Comment by nhmkdev** [comment]
First draft of the change is complete. This should be in a future release.

**Comment by xetra11** [comment]
You are a legend buddy! I try to contribute a PR in the future - since I am becoming a poweruser with card maker :P

**Comment by nhmkdev** [comment]
Closing this for now (included in the 1.1.0.0 alpha9 build)
