### ISSUE TITLE
[Feature Request] Add defines as define references instead of naming convention "_defines"

### ISSUE THREAD

**Issue by xetra11** [nhmkdev/cardmaker#78]
Hey again!
While using CardMaker extensively I figured out that the way Defines are included is somewhat cumbersome.

I have now three different .csv files that all have the same define variables. But for each .csv file I have to bring up a copy that has the "_defines" suffix. 

I'd love to see a way to add defines just like one can already add different references!

Thanks a lot

**Comment by nhmkdev** [comment]
I like the idea of supporting multiple defines (in addition to keeping the existing functionality). Will check it out!

Are you using the project wide defines file/sheet now? That's one way currently to share across the layouts.

**Comment by xetra11** [comment]
@nhmkdev 
The project wide? I am using the one mentioned in the wiki. That is the one that has the naming convention suffix `_defines`. 
Also I am using the latest stable release - not using the pre-releases yet fyi

**Comment by nhmkdev** [comment]
Check out "Project Wide Defines" in the manual. Basically you can have a defines file named the same as your project (.cmp) Example:

my_project.cmp
my_project_defines.csv

The defines will be available in every layout.

**Comment by xetra11** [comment]
Found it!
Yeah that works fine as well. Then my request was kinda useless :()

**Comment by nhmkdev** [comment]
Okay. I'll probably close it out for now. Someone can always request it again!
