### ISSUE TITLE
[Feature] Global Elements

### ISSUE THREAD

**Issue by xetra11** [nhmkdev/cardmaker#79]
As you can see I have multiple layouts in use. Very often I have elements in all of them at the same position. Still I have to adjust them in all layouts if I make a change to the design.

It would be nice to have a way to globally define elements so I only need to adjust them once and not for every layout!

![image](https://user-images.githubusercontent.com/8149023/82094525-89bd5380-96fd-11ea-8f70-73cf6411f3e3.png)

**Comment by nhmkdev** [comment]
I'm thinking of a couple of options for how to approach this. I am leaning towards something like adding a _reference_ element. These would be elements that you create in one layout but reference in others. Any changes made to the element in any of the layouts would affect the original... BUT also you can use overrides in the reference data if you need to customize the element in a given layout (like tweaking the location etc).

It's a fairly complex change so it might be a while before there's much progress.

As a cheap work around I would suggest using some global defines mixed with in-reference overrides. It's fairly painful but at least unifies a little bit.

**Comment by xetra11** [comment]
as a current workaround I use the Copy/Paste functions on the elements. However only "Paste Settings" seems to work in my case

**Comment by nhmkdev** [comment]
I've started to work on this! The core functionality seems to work. A referenced element can be adjusted on any Layout and it will affect the original. The original has to exist of course...

When I have something a bit safer to demo I'll make a release with it.

**Comment by nhmkdev** [comment]
Here is a preview of the reference functionality for initial testing.

**DO NOT USE THIS WITH ANY EXISTING PROJECTS WITHOUT BACKUPS. IT IS A BAD IDEA.**

There are still some outstanding issues etc. to work out.

Quick Instructions:
1. Copy an Element from a layout
1. Select Paste Reference(s) to create a reference element in another layout (the name MUST match the original)
1. Move around the reference element (marked with a `*`)
1. Check out how the original layout is affected!

[CardMaker_1.1.0.0_UNSTABLE_A13X.zip](https://github.com/nhmkdev/cardmaker/files/4882329/CardMaker_1.1.0.0_UNSTABLE_A13X.zip)

**Comment by nhmkdev** [comment]
Closing out old bugs/issues.
