### ISSUE TITLE
[BUG] Permanent black outline even in exports

### ISSUE THREAD

**Issue by xetra11** [nhmkdev/cardmaker#80]
Version used: v1.0.0.2

When I export something that has a transparent outline (with "Export Transparent Background" = true) it happens that the black outline of the initial project stays in there.

Here it is in the Editor:
![image](https://user-images.githubusercontent.com/8149023/82142049-e160d980-9839-11ea-9c7e-477153b0929f.png)

And here on the exported card (Windows 10 view):
![image](https://user-images.githubusercontent.com/8149023/82142060-f5a4d680-9839-11ea-876b-8e445abedf66.png)

Also opened the exported file in Gimp to verify - it indeed is there.

Would love to know how to get rid of it

**Comment by nhmkdev** [comment]
I was seeing this too and believe it is addressed in one of the unstable releases. Can you make a backup of your project and try loading/exporting with [1.1.0.0.A10](https://github.com/nhmkdev/cardmaker/releases/tag/v.1.1.0.0-unstable.v.a10)?

Though I think at the time it was just related to the border export... not necessarily the transparent background.

**Comment by nhmkdev** [comment]
Closing out old bugs.
