### ISSUE TITLE
[BUG] 800 DPI not allowed as MAXIMUM

### ISSUE THREAD

**Issue by xetra11** [nhmkdev/cardmaker#81]
ArgumentOutOfRangeException was thrown as soon as I try to use 800 DPI.

Stacktrace: https://pastebin.com/Hzu3uNve

**Comment by nhmkdev** [comment]
Ha yea the limit is 600. I'll bump it to 6000 for a future build.

**Comment by xetra11** [comment]
Over 9000

**Comment by nhmkdev** [comment]
This is 6000 in the new 1.1.x builds.
