### ISSUE TITLE
[BUG][Version 1.1.0.0 V.A11-1] Can't access Google Spreadsheet anymore

### ISSUE THREAD

**Issue by xetra11** [nhmkdev/cardmaker#82]
I wanted to try out the new command line features but already stumble over the google sheets reference.

Version: Version 1.1.0.0 V.A11-1
OS: Windows 10

Steps to Reproduce:
* Start Cardmaker
* Rightclick Layouts/Default
* Choose "Add Google Spreadsheet Reference
* Popup appears telling me I have nothing configured -> clicking "OK"
* Google Credentials Dialog appears
* Click "Browse To URL"
* Continue through Googles Dialog for choosing Google User
* Copy Token from https://www.nhmk.com/cardmaker_oauth2_v2_request.php
* Paste Token into CardMaker Credentials Dialog
* Click OK
* Nothing appears under Layouts/Default
* Trying to Redo the Process
* Error Popup appears
![image](https://user-images.githubusercontent.com/8149023/82557052-446cac00-9b6b-11ea-8d0d-156dfd497469.png)

Log Output:
```
13:55:30.61::Auto-Save Disabled
13:55:31.11::Cleared Undo/Redo.
13:55:31.12::No existing file specified. Loading defaults...
13:55:31.12::Cleared Undo/Redo.
13:56:17.10::Deck Translator: Incept
13:56:17.21::Cleared Undo/Redo.
13:58:45.28::General exception: The access token has expired but we can't refresh it
```

**Comment by nhmkdev** [comment]
> 13:58:45.28::General exception: The access token has expired but we can't refresh it

That's really disturbing... I tried this all out and it appeared to work for me. Is there anything unique going on like the time on your computer is off or something special about your timezone (any related regional time shifts)?

**Comment by xetra11** [comment]
@nhmkdev 
I am using `CardMaker_1.0.0.2` as the current working version.
I can't tell anything about weird timezones. Never changed it and it looks ok.

**Comment by xetra11** [comment]
@nhmkdev 
Can you give me info of your system?
Browser, OS, etc? I really want this feature to work! :(

**Comment by nhmkdev** [comment]
Win10 + Chrome in this case.
Hitting https://www.nhmk.com/cardmaker_oauth2_v2_request.php

On the resulting page it indicates an expires in amount. 
Mine says: 
> Expires in: 3599ms

To be super clear this is what you're seeing:
- 1.1.0.0 V.A11-1 + Google **does not work**
- 1.0.0.2 + Google **does work**

You could remove the application from your account and re-add it if necessary (a bit risky): https://myaccount.google.com/permissions (I'd be cautious if 1.0.0.2 is working though!)

**Comment by xetra11** [comment]
I removed it now.
Unfortunately no bettering. Same process - I can click my way through the auth token dialogs etc. and no error appears. However at the end there is no spreadsheet reference appearing:

![image](https://user-images.githubusercontent.com/8149023/82688803-c3d8a900-9c59-11ea-805c-9d02d3434efa.png)

Retrying the whole results in the error dialog (shown in the first post)

**Comment by nhmkdev** [comment]
So you were able to select your spreadsheet/sheets? Then it broke down? If so, that implies the token was ok but then something else went horribly wrong. There was an issue a while back where users with duplicated spreadsheet name had issues...  Are you still getting the exact same errors in the logs about _access token expired_?

I'll have to check it out later.

**Comment by xetra11** [comment]
Ah no. There was no spreadsheet selection. After I pasted the auth token and pressed ok nothing followed. Yeah it should've shown me the dialog for the spreadsheet selection - that was not the case here

**Comment by nhmkdev** [comment]
Do you happen to have another computer you could try on? I tried on another computer to make sure there was no cache or anything... still worked there for me. :(

**Comment by xetra11** [comment]
@nhmkdev 
I only have an Pop_OS Linux. That won't help to find the problem I am sure.
What Timezone do you use? I am on UTC+1

**Comment by nhmkdev** [comment]
I'm on PDT (UTC-7 right now). I dunno why Google and your computer are not agreeing on the token expiration time... that's so frustrating.

**Comment by nhmkdev** [comment]
Hahaha I got the error in a virtual machine by changing to UTC+1 (Amsterdam, Berlin, etc).

I'll see if I can learn anything else. That's so amazingly bad.

**Comment by nhmkdev** [comment]
Ok so if your time is configured as anything UTC+X it fails. UTC+0 and UTC-X all work. 

👎  Will investigate a fix (assuming there is one).

This is all likely due to all the changes Google required me to make. [Google Sheets Deprecation and CardMaker](https://www.boardgamegeek.com/thread/2286426/warning-google-sheets-v3-api-deprecation-march-202)

Looks like they didn't deprecate it yet it...

**Comment by nhmkdev** [comment]
And... easy fix. Get [1.1.0.0 V.A11-2](https://github.com/nhmkdev/cardmaker/releases/tag/v.1.1.0.0-unstable.v.a11) and it should work now.

Thanks for your patience and help narrowing it down!

**Comment by xetra11** [comment]
Fix is a touchdown - Thanks!
