### ISSUE TITLE
[BUG] override:[elementname]:horizontalalign - does not work

### ISSUE THREAD

**Issue by xetra11** [nhmkdev/cardmaker#83]
Version: 1.0.0.2
I the following override `override:[elementname]:horizontalalign`. I tried the following values:
* Center
* CENTER
* center
* different numbers (1,2,3)

Might it be that I got the attribute name wrong? The only reference for attribute codes I could find was this here:

![image](https://user-images.githubusercontent.com/8149023/82728726-9f7cdb00-9cf2-11ea-8d5f-01c35fbaa869.png)

**Comment by xetra11** [comment]
@nhmkdev 
Any way to contact you regarding developing? I just checked out the project. Maybe I can fix some stuff I stumble over and add Pull Requests. Still need to ask questions if in doubt tho

**Comment by nhmkdev** [comment]
For development just add bugs and if you want to investigate the issue call it out in the bug.

As for your align issue I configured the following column in the sample.csv included in the app zip file:
`override:title:horizontalalign` and it worked as expected

The **Card_Maker.pdf** has a section called **Element Overrides** with a table of all the element attributes you can override and what values to specify:

**horizontalalign**

(int) Numeric value indicating the horizontal alignment:
0 – Near
1 – Center
2 – Far

You will need to specify the alignment using the int values indicated (at least until I decide that's too annoying). Let me know if the ints don't work for you.

**Comment by xetra11** [comment]
@nhmkdev  works fine with the int!
Thanks a heap!

Btw. is there a way to donate to your effort? I'd love to!

**Comment by nhmkdev** [comment]
@xetra11 
Donations / Gifts -- If you really want to: gift via Paypal to nhmk@nhmk.com
