### ISSUE TITLE
[Feature] Override in Editor

### ISSUE THREAD

**Issue by xetra11** [nhmkdev/cardmaker#87]
We have currently have that functionality to override in the "Excel Reference" by ```override:element:field```.
However I'd love to have the same with the in-editor elements as well.

For instance:

I have an element "Illustration" that is of type "Graphic". It represents the Artwork of my card design. Some artworks will not fit with the same X/Y/Width/Height setup - so I have to adjust it very often.
The issue is that I always have to use ```override:illustration:x``` and so on.
With about 150 cards and every illustration to realign that becomes very tedious.

What I'd like to do is just browse every card - and drag the illustration by hand and step over to the next one in the editor.
That would be possible if I could override or have for every "Illustration" Element a separate value setup for every card row.

Hope the idea is clear!

**Comment by nhmkdev** [comment]
🤔 

This is a tough case. CardMaker doesn't do 2 things that would be critical to supporting this:
1. Doesn't write to reference files / spreadsheets
1. Doesn't store any information on a per card basis (only at the layout level)

The best option to fulfill this request would be to write the overrides into the reference file for the user. Unfortunately writing to references is non-trivial (no thanks to all the hoops I personally had to jump through to get permission to even have the application read a Google sheet).

A slightly more awkward approach would be to have an in-application set of overrides and allow the user to easily copy them out and paste into whatever reference they are using. Basically the flow would be like this:
1. Offer some way to indicate an element value override in the application on a per card basis
1. Offer a way to copy out the overrides for the entire layout/deck.
1. User pastes in the entire override column into their reference.

I guess another thought is just a general curiosity... is there anything else that CardMaker could do to make working with your images easier? It seems like having to tweak each one implies an issue CardMaker might be able to help with in a more automated way.

**Comment by nhmkdev** [comment]
Closing out old bugs.
