### ISSUE TITLE
Running on Linux?

### ISSUE THREAD

**Issue by kovasap** [nhmkdev/cardmaker#88]
I noticed some references to a Linux build in this repo, but am not sure if I see one in the releases.  Did I miss something?  Or are there instructions somewhere for building from source on Linux?

**Comment by nhmkdev** [comment]
There is a mono executable included with each release. It has been lightly tested as it has many limitations (and likely problems). The readme.txt includes some information related to the installation of mono but those instructions may differ. I'll probably add a page to the wiki about running with mono.

**Comment by kovasap** [comment]
Ah ok, I was unfamiliar with Mono.  For future reference, you can just run the CardMaker_Mono.exe on the command line with:

```
mono CardMaker_Mono.exe
```

You may need to install `mono-complete` to get access to the proper Windows Forms library.  I did this with `sudo apt-get install mono-complete`.
