### ISSUE TITLE
Text fields don't render on Linux

### ISSUE THREAD

**Issue by kovasap** [nhmkdev/cardmaker#89]
I'm having an issue where text fields from my csv seem to be importing properly, but the text in the csv does not render on the exported images or in the WYSIWYG Canvas panel.  I can see the values of each row in the Element Control panel table, which seems to be working as expected.  I don't see anything strange in the on screen log.  I've tried multiple common fonts (e.g. Ariel).

I'm running CardMaker_1.0.0.2 on a Debian Linux with `mono-complete` installed.

Any idea for what could be causing this problem or things I could try to fix it?

**Comment by nhmkdev** [comment]
I've only really tried with ubuntu unfortunately. Can you try running with one of the newer releases (pre-releases) and see if it makes any difference? Is there anything displayed in the console/terminal window when running? Sometimes there can be interesting extra information logged there.

I am guessing the included sample project also does not work at all...

**Comment by nhmkdev** [comment]
I installed Debian 10.5.0 in a VirtualBox VM. I only had access to certain fonts so CardMaker switched over to the Liberation Sans (...) fonts. This is running with CardMaker 1.1.0.0 A13. It still rendered though... 

![image](https://user-images.githubusercontent.com/6293880/93954619-ed3a3c00-fd02-11ea-8714-6d8bc1308378.png)

**Comment by kovasap** [comment]
Hmm, it still doesn't work for me.  I'm on a custom Linux distribution that is based on Debian though, so I might be missing a certain package that will make it work.  I'll update this bug if I figure it out.

**Comment by kovasap** [comment]
Actually i'm having the same problem on windows now too!  Perhaps my project/csv files are the culprits?  Can you reproduce with them?

[repro_data.zip](https://github.com/nhmkdev/cardmaker/files/5288840/repro_data.zip)

**Comment by nhmkdev** [comment]
> 
> 
> Actually i'm having the same problem on windows now too! Perhaps my project/csv files are the culprits? Can you reproduce with them?
> 
> [repro_data.zip](https://github.com/nhmkdev/cardmaker/files/5288840/repro_data.zip)

Thanks for the data! It appears you need to configure your definitions on the elements to associate with the column from the `resources.csv`

In your case the element named `name` should have this definition value: `@[name]`
`tier` should have this definition value: `@[tier]`
The same is true for the rest of the elements and columns. You can also have other characters in the definition as necessary.

Take a look through the [Basic Deck](https://github.com/nhmkdev/cardmaker/wiki/user-basic-deck) for some more information too. 

I hope that helps!

**Comment by kovasap** [comment]
Ah yes that was my problem, this all makes much more sense now.  Thanks for all the help, and sorry for not reading the documentation more closely : ).
