### ISSUE TITLE
[BUG] Inconsistent Resolution for Inline Images

### ISSUE THREAD

**Issue by FelChado** [nhmkdev/cardmaker#91]
First of all, I really wanna thank you for your work! I'm loving this software and I've been using it for some months now for a card game project. I've been testing it for some time and I'm close to releasing it for free on Tabletop Simulator.

That said, I don't know if you're taking requests right now, but there's a single graphical problem I still couldn't solve when exporting my cards.

When using inline images in my Formatted Text objects, their appearance gets inconsistent after exporting. For example, [in this card](https://i.imgur.com/cFZ90QQ.png) you can see the square symbol I use in its text takes 2 different forms. You can see it taking another appearance [in a different card](https://i.imgur.com/biA4cXH.png).

I've tried a lot of things to solve this, such as increasing and decreasing the image's resolution drastically or passing arguments for offset and size to the inline images. 

That's the only graphical glitch I'm facing on my game right now, and I know you're doing this for free, but I would love if you would tell me a way to solve this (maybe I'm doing something wrong).

**Comment by nhmkdev** [comment]
Fascinating (and annoying for you!). 

Is the expected display the "then get a [] +1" in the first card?

Are the cards rendering the box using the same element? What is the data for those elements along with the element definition?

Are you exporting to any specific file format (png I am guessing)? 

Any specific DPI (not that it should matter for an individual image export)?

**Comment by FelChado** [comment]
Wow, thanks for the fast response!

1 - The expected display would be the second square in the first card.
2 - They're using the same element. I'm currently using [this sprite](https://imgur.com/a/VHROt87) though I've tried many others. I'm defining the element like this: <img=/Card Graphics/dice.png>
3 - It's a .png file.
4 - Hmm I don't know how to check the DPI, I don't see that option on export.

**Comment by nhmkdev** [comment]
The DPI is a setting on the layout by width/height (should not apply but just checking).

Is your element using Auto-scale?

What version of CardMaker are you running?

**Comment by FelChado** [comment]
1 - Thanks, I've found it now, it's 100.
2 - No, it's a FormattedText object, and from what I see it doesn't have the option to Auto Scale, unlike normal Text.
3 - I'm using 1.0.0.2, but I also tried to export it on the latest version (1.1.0.0 VA14) and the same thing happened.

**Comment by nhmkdev** [comment]
Final question: what font are you using and what size?

**Comment by FelChado** [comment]
The font is [Coder's Crux](https://www.dafont.com/coders-crux.font), the size is 11 in a FormattedText element. Sorry for taking so long, it was pretty late here!

**Comment by nhmkdev** [comment]
I'm going to look into this a bit more but it appears the .NET renderer does some really odd things based on where the image is drawn and how the scaling to the image is applied.

Random thing to try:
```
<img=/Card Graphics/dice.png><push=3>
```
Try adding the push tag in one of the problematic cards with values from 1-10 and see what happens. It's a strange suggestion but it seemed to have an impact when I tried it locally.

Likely unrelated observation: The image you are using has extra transparent pixels at the bottom. I doubt that is impacting things... but I am just guessing at this point.

**Comment by FelChado** [comment]
Thanks for looking into this! I'll try this suggestion and I'll get back with you with the results.

About the transparent pixels, I did them before I learned how to offset inline images. I tried exporting without them too after learning about it, and the problem still happened. I'll remove them anyway as using offset in the Y axis is the better approach.

**Comment by FelChado** [comment]
About the "push" solution. Some cards were affected by some push at some values (and sometimes also adding push before the image) and got fixed, some other didn't get affected. It definitely can affect inline image resolution.

**Comment by nhmkdev** [comment]
I've done a bit more research and if the font size is 11 the scaled inline image size ends up about 6x8 with the [image](https://imgur.com/a/VHROt87) you provided. I suspect the original size (40x52) being scaled so much is the likely cause. This is local to my machine so things might differ for you...

Are the full card images you included in the original post scaled up in size? I had to scale my versions dramatically to get to the same view with the font at size 11. Do you have windows set to scale fonts to a percent other than 100%?

**Comment by FelChado** [comment]
Yes, I've scaled the cards' sizes 4 times after exporting. That was so you could see the squared icons more easily in the first post, but I see how it might just have caused confusion, sorry.

About the scaled inline images being about 6 x 8 in the exported card: that's very interesting, an probably very related to the problem. The square I was using was a 40 x 52 image, which means its ratio is 10 / 13 which is incompatible with the final size in the exported card (6 x 8). That means its appearance is going to vary from card to card and get inconsistent.

So now I'm experimenting with using different ratios with this image, ratios that respect its final 6 px width in the final image, and I'll soon get back to you with the results.

**Comment by FelChado** [comment]
Okay, I managed to get the image exactly the same in every card. So now I'll describe the steps I took.

First, I tried to use a 6 x 8 image, and it got blurred like I described above until I multiplied the image by 4. Result: Almost all cards got ok, but some cards still got a little pixels off on the square image.

Then, I tried a 6 x 6 and got similar results, only I noticed the square image was getting resized to 8 x 8 in the exported card. So I tried changing the square sprite to 32 x 32 (which is a 8 px square times 4). The result was very interesting: Almost all cards got the it right, but some of them still were a little off. 

This is an [example ](https://i.imgur.com/O3J9fqx.png) of a card that got it right, with a 8 x 8 sized white square on its text. [This one] (https://i.imgur.com/Wx8faGZ.png) got it a little off, because its size is 9 x 8. [This one](https://i.imgur.com/YllcxWb.png) also missed its height, being a 9 x 9 and also creating graphical glitches. 

So in order to reinforce that the right width/height is 8, I set these properties on the image: 
<img=/Card Graphics/dice.png;0;-1;8;8>

The result was that now the square's size was **always** 8 x 8. So now how are the previously problematic cards behaving? Now, the size of their square icons is right, but they still have some [graphical problems](https://imgur.com/a/rxMg36g) of having wrong colored pixels. 

That was finally solved by increasing the icon's image size from 32 x 32 to 64 x 64! Now everything is perfect.

What is even more interesting is that after increasing the image to 64 x 64, I don't even need to set the image's properties (<img=/Card Graphics/dice.png;0;-1;8;8>) anymore, and everything stays fine.

Thank you for your time and for helping me! I hope showing this process also helped understanding the issue a little more. 

I've noticed this problem after adopting a pixel art aesthetic for my game, but I'm pretty sure it was happening before too. I believe it's related to the inline image forcing a certain aspect ratio the original image can't adjust itself to, so these inconsistencies start happening.

Again, thank you and I'll definitely credit this tool after posting my game. I'll also contact you to let you know when that happens.

**Comment by nhmkdev** [comment]
Great I'm glad you found a solution that worked out! Thank you for all the details and information.

The code I've been adding logging around involves the resizing based on aspect ratio. A couple of factors that likely contribute to issues with especially small images like the square:
- The aspect ratio is calculated with floats (non-whole numbers)
- The target width and height are also floats (non-whole numbers)
- Working with whole numbers at any step of the way will give even worse results! 

I would definitely suggest users specify the width&height on smaller images and map out which sizes are valid for their images (if they plan to have small/medium/large). The extra parameters on the `img` tag were a necessary evil, especially for smaller images when I added the inline functionality. I'm glad they helped a bit, even if you found in the end the 64x64 was fine without. 👍 

Best of luck!

**Comment by nhmkdev** [comment]
Closing out old bugs.
