### ISSUE TITLE
"Basic" cannot be used as a define.

### ISSUE THREAD

**Issue by Kuroiryu146** [nhmkdev/cardmaker#94]
I set "Basic" as the define in my defines csv and it wouldn't pull the corresponding value. When I changed "Basic" to "afart" and added "@[afart]" to my reference csv, it pulled correctly. Occurs in v1.1.0.0.

**Comment by nhmkdev** [comment]
I tried this locally without issue. Is there anything else named basic in the defines/elements/layouts? What type of element are you using the @[Basic] in?

**Comment by Kuroiryu146** [comment]
Nothing else named Basic. When I look at the defines list from within the software, sorted alphabetically, it doesn't appear. It skips over it no matter where I place it in the list in the CSV. I tried calling it from a Text element and a Formatted Text element. I set the define to call both a regular string and an <img> to no avail. I've got about 40 other similar defines working just fine. It's very specifically that spelling of the word. Even "Basicc" works.

**Comment by nhmkdev** [comment]
So strange!

If you wouldn't mind sending me a CSV with the issue I can double check there's nothing odd going on.

**Comment by Kuroiryu146** [comment]
This is my first time actually using github so I'm not sure how you wanted me to share it but I chucked the csv into a repository and invited you to it. I'm sure there was an easier way...

**Comment by nhmkdev** [comment]
Apparently you can drag and drop files into this text editor (I didn't know that either!).

Unfortunately I was not able to reproduce the issue with the file you uploaded. I guess one final thing to check is if there are any warnings in the log window when you load the project or access a layout that uses the define.

This is definitely a tough one to figure out!

**Comment by Kuroiryu146** [comment]
> Apparently you can drag and drop files into this text editor (I didn't know that either!).

I tried that first, but it didn't like the CSV file type.

> the log window when you load the project

Success! 

`10:14:36.06::Overlapping column name and define found in: ... [5]: Basic`
