### ISSUE TITLE
[BUG] Excel Reference files produce errors when containing certain functions

### ISSUE THREAD

**Issue by ramzes222** [nhmkdev/cardmaker#97]
When attaching an Excel file as a Reference, if the sheet contains the function SWITCH, no rows will load and the reference data will be blank.

This does not happen with all functions - for example, IF statements load correctly (if anyone else runs into this problem before it is fixed, a complex IF statement can theoretically replace SWITCH with the same functionality)

This also only affects that spreadsheet. Other spreadsheets in the same file will still load correctly

**Comment by nhmkdev** [comment]
Interesting! I did not realize SWITCH was a newer function of Excel (as of Excel 2019) - [Microsoft Site on SWITCH](https://support.microsoft.com/en-us/office/switch-function-47ab33c0-28ce-4530-8a45-d532ec4aa25e). It is likely the open source functionality to read Excel files included in CardMaker is old enough to not recognize/support it either ([ClosedXML](https://github.com/ClosedXML/ClosedXML/releases/tag/0.94.2)).

As a workaround (for now), can you use the switch logic provided in the CardMaker application?

```
#(switch;key;keytocheck1;value1<repeat>)#
```

 (see the manual for more info)

**Comment by nhmkdev** [comment]
This appears to be functional after an upgrade to the latest ClosedXML. Check it out in the latest pre-release [CardMaker v.1.2.0.0-unstable.v.a7](https://github.com/nhmkdev/cardmaker/releases/tag/v.1.2.0.0-unstable.v.a7)
